### ISSUE TITLE
Server side Sorting 

### ISSUE THREAD

**Issue by skrajath** [AllenFang/react-bootstrap-table#1004]
I was following this https://gist.github.com/AllenFang/d26a733870c11c2163161fc22042ba6f#file-manage-sort-table-jsx and i have noticed this
I have server side sorting of data. server call is made in onSortChange and the returned data is set to table.
So clicking on Header, this happens
(1) Current data/rows displayed in table gets sorted and
(2) Once the call to server is back in onSortChange, the table data is modified again

Ideally (1) should not be happening. Also this happens only for the first time clicking on the header for sort. On consecutive clicks on header (1) is not seen.
So, is this right way of server side sorting ?

**Comment by AllenFang** [comment]
In your case, you should use `remote` model, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-sorting.js and https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-sorting.js

enable `remote` on `BootstrapTable` which is you want control the data changing, paging, sorting, CRUD, etc on your flux implement or anything instead of `react-bootstrap-table` itself.

let me know if you got any trouble on implementation, thanks

**Comment by skrajath** [comment]
@AllenFang Thanks. The `remote ` on `BootstrapTable ` did the trick and it works fine now.

**Comment by nirmalasubu** [comment]
@AllenFang  Is it possible to bring bootstrap table pagination to center instead of float :right?I see possibility of adding pagination either top or bottom page.

**Comment by AllenFang** [comment]
@nirmalasubu, we dont support this feature, but you can custom it, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/pagination/custom-pagination-panel.js, you can do everything your want.

**Comment by nirmalasubu** [comment]
@AllenFang  Thank you. I'll give it a try.
