### ISSUE TITLE
Reactbootstrap table not working with redux form

### ISSUE THREAD

**Issue by knnemade99** [AllenFang/react-bootstrap-table#1016]
I am using react-botstrap-table version "2.11.2".
Issue: 
I integrated the react bootstrap table with redux form. When the first time it loads it works fine. But when it goes from current Page(Bootstrap Table component) to next page(any Random Input Field) in redux form and again come back to previous page(Bootstrap Table component) which contains react bootstrap table, It shows the following error: 

Uncaught TypeError: Cannot read property 'id' of undefined
###     at TableBody.<anonymous> (http://10.19.4.105:8383/index.js:42586:33)
    at Array.map (native)
    at TableBody.<anonymous> (http://10.19.4.105:8383/index.js:42585:48)
    at Array.map (native)
    at TableBody.render (http://10.19.4.105:8383/index.js:42584:40)
    at http://10.19.4.105:8383/index.js:16369:22
    at measureLifeCyclePerf (http://10.19.4.105:8383/index.js:15648:13)
    at ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext (http://10.19.4.105:8383/index.js:16368:26)
    at ReactCompositeComponentWrapper._renderValidatedComponent (http://10.19.4.105:8383/index.js:16395:33)
    at ReactCompositeComponentWrapper._updateRenderedComponent (http://10.19.4.105:8383/index.js:16319:37)

When I write the following function: 
      shouldComponentUpdate() {
          return false;
      }
in my bootstrap component class then The table works fine and no error will come when moving to next or previous page in redux form.

But as I searched for this function, almost I found that we should avoid use of this function.

So kindly please provide me any better solution for this and also let me know why this problem is coming.

**Comment by AllenFang** [comment]
> But when it goes from current Page(Bootstrap Table component) to next page(any Random Input Field) in redux form

I'm not familiar with `redux-form`, in this description, do you means `redux-form` change the url to another page and back it again right?

For you workaround, you don't let the component render again, because when url back to previous page, redux will render container again with specified data from store, so you can avoid this error.

my question is did you enable the `remote` on `BootstrapTable`? I wanna check your codes so taht I can help you and I also want to know how did you redirect between different page?

BTW, because I'm not familiar with `redux-form`, so if could you please show me a simple and minimal repo for me to reproduce this issue?  thanks

**Comment by AllenFang** [comment]
close it due to no response with more than 10 day
