### ISSUE TITLE
TableHeaderColumn - DataField

### ISSUE THREAD

**Issue by meghanarora** [AllenFang/react-bootstrap-table#1018]
Can I pass multiple parameters for my data field or a whole object??

The function that renders in a column requires more than one parameter!

**Comment by AllenFang** [comment]
> Can I pass multiple parameters for my data field or a whole object??

yes you can, and use `dataFormat` to format you cell, BTW, I dont suggest user to use an object in `dataField`, because it will lost some functionality, like insert row, sorting(But you can fix it with custom sort), cell editing(You can also fix it this custom cell editing) etc. Anyway, some user doesn't need these functionality, so they still pass an object to `dataField`. So just watch out that you need to pay more effort on it

And if your field is not a object, you can check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-format/extra-data-column-format-table.js this example, it's best solution

Let me know if you got any trouble on implementation
