### ISSUE TITLE
Hide only pageList buttons, if data is placed on one page

### ISSUE THREAD

**Issue by jmorozov** [AllenFang/react-bootstrap-table#1046]
Hello! I tried version 3. And it is very cool. But I would like to be able to hide only pageList button if data is placed on the one page (and SizePerPage and Total are visible). I have not found a way to do it now.
For example as a parameter in the options like hideSizePerPage. It would be great. Thank you for your work!

**Comment by AllenFang** [comment]
@jmorozov, sorry we dont support this config to hide the pagination list if the only 1 page there. BTW, did you have custom the pagination panel by `options.paginationPanel`, if you did, I think you can hide the pagination list by yourself, because it provide full ability for you to custom.

Anyway, I think I can just support this feature by a options, but it'll be release with `v3.0.0` instead of `v2.x`, I've stop all the development on `v2.x` and ready to release `v3.0.0` to production.

Thanks

**Comment by AllenFang** [comment]
Fixed on `v3.1.0`, use `options.hidePageListOnlyOnePage` and assign true will hide page list if only one page here.
