### ISSUE TITLE
how to handle dataField that is not in data object

### ISSUE THREAD

**Issue by phamj88** [AllenFang/react-bootstrap-table#1056]
Sorry if this has been asked before. I couldnt find anything in the searches.
I have some generated columns based off of row data.
ex. 

`<BootstrapTable ref="table" data={this.props.home.data}  pagination={true} hover={true}  exportCSV search multiColumnSearch >`
`<TableHeaderColumn dataField="tot_runs" dataAlign="center" dataSort={true} width='10ch'>Total</TableHeaderColumn>`
 ...
`<TableHeaderColumn dataField="pending" dataAlign="center" dataSort={true} dataFormat={Formatters.pendingFormatter} >Pending</TableHeaderColumn>`

Formatter:
`export function pendingFormatter(cell, row){
     return row.tot_runs - row.tot_fail_count - row.tot_incomplete_count - row.tot_pass_count
}`

so "pending" does not exist in the data object.
Is this the correct way of doing that?

I am asking because I am getting issues with sorting and searching for only the columns that don't exist in the data object. It is not able to sort the pending field but all other fields in the data object sort fine.

![test](https://cloud.githubusercontent.com/assets/25780505/23075634/db7a92fa-f502-11e6-9d2a-409b4bc4a0a3.gif)

**Comment by AllenFang** [comment]
@phamj88, yap, I don't suggest to do this if you enable sort, filter or search. I prefer you to preprocess your data before feed to table or use `formatExtraData`(https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-format/extra-data-column-format-table.js) as a workaround.


BTW, I got another solution, 

1. use `filterValue` to define the target value you want to be filter or use `filterFormatted` to filter the formatted data instead of origin data.
check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/search-format-table.js#L51-L52) or document

2. custom a your own sort function to avoid this issue, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/custom-sort-table.js) to learn how to custom a sort function.

Let me know if you have any concern or problems.

**Comment by phamj88** [comment]
Thanks for the reply Allen!
I think you're right with pre-processing the data before feeding it to the table.
Its cleaner and reduces having to implement filter,export,and data formats.

Thanks for the reply! I feel stupid not thinking of that
