### ISSUE TITLE
Improve pagination when using browser's back button, so pagination isn't reset

### ISSUE THREAD

**Issue by jflayhart** [AllenFang/react-bootstrap-table#1093]
For example, a Users page has a table with 10 pages worth of users, you go to page 4, decide to click on a user and are re-directed to that user's page. You decide to hit browser's "back" button to go back in history to the Users page again. I would expect the table to show the 4th page of users, where you last left off in this scenario, but instead the table is reset.

I thought of doing some thing like create a temporary redux store to cache page and pageSize per table, but this is difficult because I only want this to work in the event you go back in browser's history to a previous table's state. Otherwise, I think it is right to reset the table's pagination state on componentWillMount.

Is this not something react-bootstrap-table should be responsible for maintaining? Or is this outside the scope of this plugin, since it may involve working with react-router?

**Comment by AllenFang** [comment]
@jflayhart, sorry for lately reply due to my long trip ;)

cache the current page and sizePerPage in redux and restore it by `options.page` is also a solution, there're some people do the same thing but he cache the sorting status

but for `react-bootstrap-table`, I've no too much idea to cache these status(page, sort, bla bla) and I'm not very sure that whether the others table component or other widget(tabs, select, list) support this kind of feature, if you see you can tell me. Anyway, this is not very important feature currently, but it's pretty worth to do for a improvement reason but need a good solution.
