### ISSUE TITLE
npm run build fails if react-bootstrap-table is enabled

### ISSUE THREAD

**Issue by Steffi3rd** [AllenFang/react-bootstrap-table#1116]
ReactJS
ES6
Webpack
Babel

-- 

In my component I have this : import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';

Then I run "npm run build" >> FAIL

If I comment or remove this line //import { BootstrapTable, TableHeaderColumn } from 'react-bootstrap-table';

Then I run "npm run build" >> OK

Why? And how to solve that? Thanks 

<img width="568" alt="capture d ecran 2017-03-06 a 02 03 31" src="https://cloud.githubusercontent.com/assets/814410/23593578/249a0298-0211-11e7-94ec-3c34123c3a38.png">

**Comment by AllenFang** [comment]
I'm not sure the root cause for this issue, but I'm sure this is not about `react-bootstrap-table`, if true, I think this is a big and known issue now, so could you please google it or try to use the same syntax to import the other package?

Let me know if you are sure this is the bug for `react-bootstrap-table`, I'll open issue again, thanks
