### ISSUE TITLE
blurToSave for custom editor

### ISSUE THREAD

**Issue by JD2k** [AllenFang/react-bootstrap-table#1118]
Hi,

iam looking for a function to realize blurToSave function in a custom editor. Didn't fount anything in the examples. Can someone help me here?

Greetings

**Comment by AllenFang** [comment]
@JD2k, if you are using the custom editor, you will lose the blurToSave functionality, because for `react-bootstrap-table`, I don't know your DOM structure and event don't know which element is your input field, event maybe you have multiple input field. so in the custom condition, you can do anything by yourself, but I can't bind the onblur event on element.

Let me know if you got any question, thanks :)

**Comment by JD2k** [comment]
Hi Allen,

thanks you are right, just thought there is a standard way to do it. 
This is my solution now:

    componentDidMount() {
        document.addEventListener('click', this.handleClickOutside.bind(this), true);
    }

    handleClickOutside(event) {
        this.updateData()
    }

    componentWillUnmount() {
        document.removeEventListener('click', this.handleClickOutside.bind(this), true);
    }

Maybe it is useful for others or for the examples.

Greetings

**Comment by shirilad** [comment]
Hi there,
Just a quick adition - I bumped into a similar need, but couldn't get the suggested solution to work from some annoying reason revolving around the actual binding,
but found another workaround which might also be of help:

Just call the necessary this.updateData() method from componentWillUnmount, Which is called anyways the moment you click somewhere else on the screen and leave edit mode.
