### ISSUE TITLE
Tying row functions to <button>

### ISSUE THREAD

**Issue by Mikeg542** [AllenFang/react-bootstrap-table#1162]
I have a table with 2 buttons in the last column (a checkmark and an X) and would like to find a way to use similar functionality to the row select but tied just to the buttons. 

For example, when the user clicks the X, I'd like to add a class to the row to grey it out or remove it. And when the check is clicked, return the rows data and make an api call with it. Any help pointing me to the relevant documentation would be very appreciated.

**Comment by AllenFang** [comment]
Sorry for lately reply, busy on this month. Fixed now? Let me know if this problems still remain.

**Comment by shanben7** [comment]
@Mikeg542 How did you resolve this? I also have a column with buttons, but I have to double click it to toggle the buttons. This is because the first click changes the cell from Format mode to Edit mode, and then the second click does the toggle. I want the first click to toggle the button, if possible.

**Comment by Mikeg542** [comment]
Right  now what I have working is:
`   interactFormatter = (cell) => {
        return <a onClick={this.removeUser} className="removeUser" data-id={cell}></a>;
    }`

  ` removeUser = (event) => {
        let id = event.target.dataset.id;
         etc etc.
    }`
    .....
   `<TableHeaderColumn dataField="user_id" dataFormat={this.interactFormatter} dataAlign="center">Remove</TableHeaderColumn>
`
