### ISSUE TITLE
Accessing column data for filtering

### ISSUE THREAD

**Issue by mswaminath** [AllenFang/react-bootstrap-table#1180]
I am trying to create a custom filter that will have a Multi select dropdown filter. I can take the custom-filter as example but it has pre-defined options like good, bad etc. but in my case, it's dynamic. What I want is to get it from the column data's and put it in the dropdown list dynamically.

Is there a way to access the column specific data's through `refs` on `componentDidMount()` **OR** can I access it through `filterHandler` props like you did for `targetValue` to apply the filter for?

**Comment by AllenFang** [comment]
so you means your dropdown is depend on only one column data(All rows)?  If yes, I think there's no tricky way to do it, you still can use `customFilterParameters` to pass your own data, but for your dynamic situation, you can do some preprocessing or pre populate before you assign data to `customFilterParameters`

BTW, ``customFilterParameters` is custom by yourself, so you still can pass a callback function, and call it on appropriate time and return your columns data.

Actually, if you really need the all columns data, I thinks I can do it, but in my consideration, it's not very necessary, because you can do it by yourself.

Let me know if you got any questions.

**Comment by mswaminath** [comment]
Yes it is possible from the user's side but if you provide the columns data then it will be fulfilled as we don't need to put extra codes and it will be just `react-bootstrap-table`'s logic.
