### ISSUE TITLE
react-addons-update

### ISSUE THREAD

**Issue by capedzillah** [AllenFang/react-bootstrap-table#1191]
hi, when im start webpack:
ERROR in ./~/@allenfang/react-toastr/~/react-addons-update/index.js
Module not found: Error: Cannot resolve module 'preact-compat/lib/update' in /home/capedzillah/front-end/new_tender/tender_analyzer/node_modules/@allenfang/react-toastr/node_modules/react-addons-update
 @ ./~/@allenfang/react-toastr/~/react-addons-update/index.js 1:17-44

**Comment by AllenFang** [comment]
It's the issue from `toastr`. 

Some refereneces:
https://github.com/AllenFang/react-bootstrap-table/issues/969
https://github.com/AllenFang/react-bootstrap-table/issues/838
https://github.com/AllenFang/react-bootstrap-table/issues/863

Actually, this related with `react-toastr` and can't be fixed in near future.

Close it due to duplicate

**Comment by AllenFang** [comment]
please check #1216, if you have any concern or question, let me know in #1216
