### ISSUE TITLE
issues with expanding

### ISSUE THREAD

**Issue by ashabi** [AllenFang/react-bootstrap-table#1206]
Hi.
I am trying to use the expanding component but I have a few issues:

1. the entire row can be clicked to open/close but it does not effect the className with this.selectRow. So therefore it does not add the class that I need nor does it remove it.
2. I would like it to close all other rows when one is selected

any help is appreciated. thanks

**Comment by AllenFang** [comment]
HI @ashabi,
1. you means `selectRow.className` is not added to the `TR`(row)?
2. duplicated with https://github.com/AllenFang/react-bootstrap-table/issues/1166

Thanks

**Comment by ashabi** [comment]
Ok. I got #1 to work. But the this.state.expanding does not seem to be updating itself when you click on the row.
#2 is a duplicate. Any idea when this will be fixed?
thanks.

**Comment by AllenFang** [comment]
could you please upgrade to newest version and try again for first issue, if the problem still remain, I think you can show me your code, thanks

for the second issue, Because there're a lots of issues need to fix so no schedule but I think I can support is in near future.

**Comment by AllenFang** [comment]
For the second issue, already release on `v3.2.0`, assign true to `options.onlyOneExpanding` to allow single expand row, default is `false`

**Comment by ashabi** [comment]
hi. thanks, but is there is a state that defines this expanding? i noticed when you click on the tr it does not remove the selectRow.className

**Comment by AllenFang** [comment]
if you found any bug or possible issue, open another issue and provide some useful information for me, I'll check it 👍 

BTW, 



> but is there is a state that defines this expanding?

I guess your answer is [here](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/expandRow/manage-expanding.js#L69) but not very sure because what's your means actually



> i noticed when you click on the tr it does not remove the selectRow.className

Actually, I dont know what's the configure for your case, please show me, and I just write a case with expanding and selection and assign `selectRow.className` and everything is work fine.
