### ISSUE TITLE
Autocomplete input field in insert Modal

### ISSUE THREAD

**Issue by genau7** [AllenFang/react-bootstrap-table#1211]
I would like to have an input text field in my Insert Modal with autocomplete functionality (given a set of values). I don't really want to implement my custom Modal - the perfect solution would be if the file Editor.js had an additional case for type 'autocomplete' or something similar.What I mean by autocomplete is something like this: https://www.w3schools.com/tags/tryit.asp?filename=tryhtml5_datalist   

Since I am new to webdevelopment and javascript in general, I wanted to ask advice if it can be done with the current react-bootstrap-table and how. Obviously I don't want to overwrite the original Editor.js file in my node_modules directory and extend it there. 
If it is not possible at the moment, could you maybe add such functionality, AllenFang?

**Comment by AllenFang** [comment]
Good question and this is need to be enhanced, because developer may only want to custom only one field but now you need to custom the body of insert modal, it's not make sense, so I'll try to support it in near future but not sure whether I can achieve it due to I remember there's some restriction here.

Duplicated issues with https://github.com/AllenFang/react-bootstrap-table/issues/1031#issuecomment-291492624

Let me know if you have any questions, thanks

**Comment by AllenFang** [comment]
HI, now we can support the custom only for input field, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/insert-modal/custom-insert-modal-field.js) example to learn how to custom it, let me know if you have any questions, thanks 👍 

Remember to upgrade to `v3.2.0`

**Comment by tyagia10** [comment]
while i am trying to get table data it is throwing me this error at the same time this property can be seen in a debugger mode, can someone please help me out why this is happening??help needed urgent

@AllenFang @genau7 @srikanthbandaru
error:
![image](https://user-images.githubusercontent.com/12757782/40356778-645dc74c-5dba-11e8-9419-9e391167f109.png)

debugger mode:
![image](https://user-images.githubusercontent.com/12757782/40356405-393abb48-5db9-11e8-98e3-eeb5900b6887.png)
