### ISSUE TITLE
How is the internal state managed?

### ISSUE THREAD

**Issue by danielstecki** [AllenFang/react-bootstrap-table#1218]
After every insert react-bootstrap-table seems to insert my new row before I set the state of the parent component with the new row which in turn renders the table with the new data. Is the internal state then reset when I rerender my table with the new state data? I am using autoValue so that the user doesn't create an ID, I then generate my own id and update the state of my app. That means that at some point the table component is using the autoValue id, but when I update the state I am using my generated ID.

I guess I am mostly just asking if I am correct about the internal state being reset when I pass in my state object, I want to make sure nothing conflicts.

Thanks for a great component.

**Comment by AllenFang** [comment]
For new added row, `react-bootstrap-table` only append new row to state and render it again, so I think you can update your data store and render table again. but maybe you can enable `remote` on `BootstrapTable`, if you enable it, you are suppose to be handled all the data change(sort, filter, search, insert, delete etc) instead of `react-bootstrap-table` internal.

But in `v2.11.1`, if you enable `remote`, you can choose which functionality for `remote` which means you can only enable row insert for remote and handle the add row by yourself.

I think you can benefit from `remote` because `react-bootstrap-table` do nothing in `remote` and also doesn't render it, so there's only one render from your application and maybe it much make sense.

Anyway, most of people use `remote` and integrate the `redux` or something like that, because some people they want to handle data from server and do pagination by themself or search their data via API etc. That's the purpose for the `remote`

you can check https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/remote to learn how to develop with remote

You can check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-alternative.js to learn how to have a alternative functionality on remote

Let me know if you have any questions, thanks
