### ISSUE TITLE
Deleting a row after insert

### ISSUE THREAD

**Issue by jcabrerazuniga** [AllenFang/react-bootstrap-table#1243]
I came to this problem: how can I delete a row that I just inserted in the react table. Why? because it failed to be saved in the database. Here it is my code:

-------------------------------------------------------------------
function handleInsertedRow(row) {
// ...
  let newRowStr = '';

  const userInfo = {};
  
  for (const prop in row) {
    newRowStr += prop + ': ' + row[prop] + ' \n';
	userInfo[prop] = row[prop];
  }
  
  delete userInfo.rowNumber;  /*eliminate dummy column :-) */
  
  console.log('JSON data = ' + userInfo);
  
  
  
  axios.post(
      'http://'+ window.location.hostname + ':9000/addNewUser', userInfo
  )
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  });
---------------------------------------------------------------------

I could not find an event like "before insert new row" as with row edition (exist?). But, if this possibility does not exist then I have to find away to delete the just inserted row through the catch section of my axios call back. Can you please tell me how can I do that?

Thx

**Comment by AllenFang** [comment]
If your data need to sync with backend, I recommend you to use the `remote` mode which let you can handle or manipulate the data by yourself instead of `react-bootstrap-table` itself. 

For some of case, people will use remote mode only for some functionality, like paging, load, delete, update, insert etc. but for filter, sort, search they hope `react-bootstrap-table` to handle it on client side.

so after `v2.11.1`, we allow `remote` mode can configure via each different functionality. for you can, maybe I guess you can only enable the insert mode for `remote`.

check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-alternative.js) and [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-alternative.js) to learn how to use it.  BTW [here](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/remote) are all the examples for `remote` mode
