### ISSUE TITLE
Not wanting the rank column to be sorted

### ISSUE THREAD

**Issue by DevAxia** [AllenFang/react-bootstrap-table#1252]
Hi,
The first column of my tables is the rank column, which should always be 1,2,3,4,5,6,... event when I sort the other columns.  How could I have this column fixed so it stays like this after sorting with other columns ?

Thank you
Pat

**Comment by AllenFang** [comment]
we dont support this kind of feature, but how about implement a custom sort function via 
`sortFunc`

you can check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/custom-sort-table.js) to see how to custom sort function.

or another advance solution is maybe you can use `remote` mode and handle the sorting on your application instead of in the `react-bootstrap-table`, thus, you can control the data.

`remote` mode is a feature to let you to do the data change(sort, filter, paging, search etc) on your application.

check this to learn how to use remote mode https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-store-sorting.js

BTW, you can only assign the sorting to use remote mode.  

let me know if you have any question.
