### ISSUE TITLE
Integration with reactstrap or bootstrap 4

### ISSUE THREAD

**Issue by tayzee** [AllenFang/react-bootstrap-table#1272]
I want to be able to use this with a bootstrap 4 project I am working on.

This is the result I get without making any modifications. Would it be a big process for me to get this to work properly?

Thanks in advance.
<img width="1000" alt="screen shot 2017-04-30 at 00 11 27" src="https://cloud.githubusercontent.com/assets/6752666/25559419/f7ae28dc-2d39-11e7-9c4b-998bf531e37f.png">

**Comment by AllenFang** [comment]
sorry for lately reply, you forgot to add the css of `react-bootstrap-table`, check https://github.com/AllenFang/react-bootstrap-table#cimport-css

**Comment by tayzee** [comment]
Thank you, yes I figured this out shortly after.
I had to import it into the jsx that im working with, originally i tried to include the cdn in my index.html file, however that didnt work.

Would there be a lot of modification required if i want to get this to work in a bootstrap 4 project?

Some elements dont position or style properly

**Comment by AllenFang** [comment]
> originally i tried to include the cdn in my index.html file, however that didnt work.

make sure you have right syntax, you can check it in chrome network to see if the css downloaded successfully or not.



> Would there be a lot of modification required if i want to get this to work in a bootstrap 4 project?

I'm not sure, we have few case in the previous, and seem like have no any big change or any broken.

**Comment by jtheberge** [comment]
Just as an update, there are some breaks between Bootstrap 3 and 4, but nothing that seems like it would take a while to fix.

Here's bootstrap 3 with a short demo:
![bootstrap3](https://user-images.githubusercontent.com/13157499/28195596-0fb36cc0-6800-11e7-80cc-720a34234173.png)

Here's the same config with Bootstrap 4:
![bootstrap4](https://user-images.githubusercontent.com/13157499/28195600-13c814a0-6800-11e7-94fb-584fba51995b.png)
As you can see, the arrows/chevrons nor the $ sign appear and the search bar gets squished (on full screen you can't read the full word Search because it becomes so small).
