### ISSUE TITLE
Column content exceed user column width definition

### ISSUE THREAD

**Issue by tbaeg** [AllenFang/react-bootstrap-table#132]
Got a lot of bugs with auto sizing the width. When specifying width in `<TableColumnHeader width='150px'/>` and cell content is large it expands past the fixed width of the column. In firefox, `overflow-x` only overflows on content rows and not header rows. Lots of weird behavior for mixed size content. Looking into fixes.. not good with `css` so going to take time.

I believe most of it is related to: https://github.com/AllenFang/react-bootstrap-table/pull/127.

**Comment by AllenFang** [comment]
there are horizontal scroll bar in your testing case? or just a simple table but apply a column width?

**Comment by AllenFang** [comment]
Briefly if the content is too large will exceed the width which user defined? maybe I need to set the <code> text-overflow</code> if a width given

**Comment by tbaeg** [comment]
@AllenFang Yes, you are correct it is exceeding user column definitions.

Also, to keep in line with bootstrap, might be wise to think about implementing the `table-responsive` class for the `overflow-x` scrolling needs.

http://getbootstrap.com/css/#tables-responsive

Personally think using as much bootstrap as possible will keep things more consistent.. it is `react-bootstrap-table` after all. :)

Let me setup a fiddle after I get a few other things working for work and get back to you.

**Comment by AllenFang** [comment]
@tbaeg, Thanks your suggestion, there're a lot of problem for css in <code>react-bootstrap-table</code> and the other is I separate the header and body with two different bootstrap table so that I suffer some layout or style problem, finally I use a lot of css or js to control my table. But at first, I think it's a better design for a rich features bootstrap table. However, I'm sure I'm not very familiar with css and responsive... ;(

Anyway, I'll study more about responsive and think how to apply to this component(It's a big change) and really thanks your any contributions :+1:

**Comment by AllenFang** [comment]
Fix it on v1.2.11

**Comment by tbaeg** [comment]
@AllenFang No problem, man. You're doing awesome work! Sorry been busy at work so haven't had a chance to reply. :(

Awesome to see this fixed. Excited!

**Comment by AllenFang** [comment]
That's fine. Actually, I need say thanks to you :)
