### ISSUE TITLE
Select filter not working properly

### ISSUE THREAD

**Issue by jennykat** [AllenFang/react-bootstrap-table#1324]
Similar issue to #517

I have the following table with a select filter on the currency column:
![image](https://cloud.githubusercontent.com/assets/2837836/26151388/544f5a14-3b0b-11e7-96dc-ec2d1c840845.png)

When I use an object like this: `{ 0: 'EUR', 1: 'AUD', 2: 'CAD' } `, in the options
as in the examples: ` {0: 'bad', 1: 'good'} `
the filter does not match any of the rows in the table:
![image](https://cloud.githubusercontent.com/assets/2837836/26151403/6cba24b2-3b0b-11e7-9aa2-ef380aa47805.png)

If I set string values as keys (same as the value), e.g.` { 'EUR': 'EUR', 'AUD': 'AUD', 'CAD': 'CAD' }`,  only then it works properly:
![image](https://cloud.githubusercontent.com/assets/2837836/26151431/8ca74a8e-3b0b-11e7-86e1-e3e03481fe61.png)

If it's not working as it should, maybe the examples/docs should be updated, showing string values as keys in the option object instead of numbers.

**Comment by AllenFang** [comment]
what's your the raw data?

**Comment by jennykat** [comment]
The data that fills the table?

**Comment by AllenFang** [comment]
ok, this is not a bug,

for the example you saw(Actually, I dont know where you got the example, but maybe is [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/select-filter-with-default-value.js)), 

you can see the quantity is a [number](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/select-filter-with-default-value.js#L20), so that we have the following select options

```js
const qualityType = {
  0: 'good',
  1: 'bad',
  2: 'unknown'
};
```

It depend on your raw data.

**Comment by jennykat** [comment]
Yes, that's exactly the example I saw. You're right, I didn't notice that quality was a number... 
Thank you very much for the quick response! I already made it work making the key the same as the value, as I said before. I thought I should report it, as I thought it was supposed to be functioning with numbers as in the example.
Keep up the good work! :)

**Comment by DerekBedard** [comment]
I made the same mistake/overlook on the key types. Thanks for all the posts here. Got my selectFilter working :)

**Comment by AshwinAchu10** [comment]
@jennykat thanks, something that i searched for is solved after searching for hours.
