### ISSUE TITLE
Question: referencing to search input box

### ISSUE THREAD

**Issue by khinlatt** [AllenFang/react-bootstrap-table#134]
Hey @AllenFang I just have a quick question.

One thing I am trying to do is to have a button in a custom component and when you click on it I want to change the input value of that search input element.

I just need a reference to that input element. I can just tag it with an id and do document.getElementById ... but

What is the correct (react) way to do so? Thanks.

**Comment by AllenFang** [comment]
I think the best solution is I export a Search module which wrap the input field, and if you want to enable search, you just render this Search component and give a ref on it so that you can get the input dom through refs. But I dont take this solution at first ;( 

In current condition, you can give a ref on <code>BootstrapTable</code> and try to find the search input field, or I can assign a <code>id</code> on search input field,

**Comment by khinlatt** [comment]
Ah I see. I'll try them out. Thanks.
