### ISSUE TITLE
Remote Combination of Search and Filter

### ISSUE THREAD

**Issue by supiash1** [AllenFang/react-bootstrap-table#1399]
Hi Alen,

I am writing remote method to achieve the search and filter using the examples available in the docs, it works fine when they are done as standalone, however when i first search and then filter, am not sure how to find the search data(if the table is searched) in the filter function to start with in your example we always start filter from complete data. I did try to start the filter with state data but that doesn't work as it would have changed depending on filter values over time,  
similar case for the other way around filter and search
could you help on this, please?

**Comment by AllenFang** [comment]
Hello, sorry for lately reply, and did you enable the `remote` mode on `BootstrapTable`?

**Comment by supiash1** [comment]
Hi @AllenFang Thanks for your response, yes i did and they works fine as standalone search and standalone filter

In your example
```
  onSearchChange(searchText, colInfos, multiColumnSearch) {
    const text = searchText.trim();
    if (text === '') {
      this.setState({
        data: this.products
      });
      return;
    }

    let searchTextArray = [];
    if (multiColumnSearch) {
      searchTextArray = text.split(' ');
    } else {
      searchTextArray.push(text);
    }

    const data = this.products.filter((product) => {
      const keys = Object.keys(product);
      let valid = false;
      for (let i = 0, keysLength = keys.length; i < keysLength; i++) {
        const key = keys[i];
        if (colInfos[key] && product[key]) {
          const { format, filterFormatted, formatExtraData, searchable, hidden } = colInfos[key];
          let targetVal = product[key];
          if (!hidden && searchable) {
            if (filterFormatted && format) {
              targetVal = format(targetVal, product, formatExtraData);
            }
            for (let j = 0, textLength = searchTextArray.length; j < textLength; j++) {
              const filterVal = searchTextArray[j].toLowerCase();
              if (targetVal.toString().toLowerCase().indexOf(filterVal) !== -1) {
                valid = true;
                break;
              }
            }
          }
        }
      }
      return valid;
    });
    this.setState({
      data: data
    });
  }
```
I think whenever a search key is entered you always start with the complete data as i assume this.products holds the complete data

Let's say I did a search for few characters and the resulting data is less than this.products

and now i want to filter on this data by column in the table, in the example below the filtering starts with this.producs which is not the result of search

```
  onFilterChange(filterObj) {
    if (Object.keys(filterObj).length === 0) {
      this.setState({
        data: this.products
      });
      return;
    }

    const data = this.products.filter((product) => {
      let valid = true;
      let filterValue;
      for (const key in filterObj) {
        const targetValue = product[key];
        switch (filterObj[key].type) {
        case 'NumberFilter': {
          filterValue = filterObj[key].value.number;
          valid = this.filterNumber(targetValue, filterValue, filterObj[key].value.comparator);
          break;
        }
        default: {
          filterValue = (typeof filterObj[key].value === 'string') ?
            filterObj[key].value.toLowerCase() : filterObj[key].value;
          valid = this.filterText(targetValue, filterValue);
          break;
        }
        }

        if (!valid) {
          break;
        }
      }
      return valid;
    });
    this.setState({
      data: data
    });
  }
```
I could start with state data but that works only for the first time, every time it does filter from search on it should filter based on the search data

**Comment by AllenFang** [comment]
Hello @supiash1, very sorry for lately reply :) ok, let going to your case, 

Actually, in the mode with `remote`, `react-bootstrap-table` will handle your case well, which means, when you search firstly and then filtering by column, `react-bootstrap-table` will do the filter base on the result of previous search. So how `react-bootstrap-table` to achieve that? Not very hard, `react-bootstrap-table`  have your all data and also save your filtered data  again, which means, in the internal, we save your original data and also have any array to save the filtered data(search + filter).

For the `remote` mode, my purpose is let you to decide how to handle/operate your data, so that `react-bootstrap-table` now is a stateless table, it only accept the data and show it, for any action(sort/filter/paging), they should be handle by you.

So back to your case, you can have an instance variable or a state to keep the last search/filter data so that you can do any action base on last data.
--------------------------
BTW, do you know the `remote` have a tricky part which is you can control which functionality need to perform as `remote` or not. you can check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-alternative.js#L11-L13) example.

in that example, it tell the `react-bootstrap-table` only `cellEdit`, `insertRow` and `dropRow` need to handle as remote but other functionality should keep to handle by `react-bootstrap-table`. For me, I usually recommend to disable some functionality which will not interact with backend, for example, insert, delete, etc. but for the sorting, filter, search, it's seems like can be don be `react-bootstrap-table` if you operation will not interact with backend server. so this example show you how to disable/enable some functionality with remote

Back to you example, after I check your code, in the filtering or search, you seems like handle the data synchronize, no any AJAX call or something, just data change in local, so maybe you can thing about to let `react-bootstrap-table` to handle search/filter and maybe make insert/delete/edit to use the remote mode if you need to sync data with backend

Sorry for a long story with my pool english, hope you can understand what I talk, and please let me know your concern to questions, thanks

**Comment by supiash1** [comment]
@AllenFang Thank you very much for the explaination, I am using only remote filter and search using  the remoteobj, 
I could have let the reactbootstrap table do the search but  onSearchChange needs to behave differently as am trying to to do search across expand tables as well

Thanks for your idea i am thinking
1) Hold the SearchData & FilterData as a variable in the state everytime it search or filter
2) Whenever we search use the FilterData if it set else the complete data similarly for filter

Thanks

**Comment by AllenFang** [comment]
> Hold the SearchData & FilterData as a variable in the state everytime it search or filter

maybe you can consider to save only the rowkeys for search/filtered data :)

Please let me know if still have any question or concern, thanks
