### ISSUE TITLE
make handlePaginationData not care if the table is empty

### ISSUE THREAD

**Issue by ofirgeller** [AllenFang/react-bootstrap-table#1431]
When I load the page I take params from the Url and update the table.

I do this on componentDidMount using 'handleSort' and 'applyFilter'.

The function handlePaginationData seems to be planned to work the same, exect that it will only update the page if the table is not empty, and at that point in time my table is empty.

What is the reason for checking for the table being empty? can we change this code, at least if the table is data is remote supplied?

**Comment by ofirgeller** [comment]
Also I would say that pagination should work like filters and sorts, they are both not controlled inputs from the perspective of the library consumer.

Setting onFilterChange and onSortChange does not mean I have to update the value of the filter input myself, why should it not be the same for pagination? this function should just be the place to do what ever needs to be done to update the data from the remote source.

**Comment by AllenFang** [comment]
@ofirgeller sorry for lately reply, if your table was empty, what was your expect when calling the `handlePaginationData`? and why the data was empty? because source or after filtered/searched? also did you enable `remote` on `BootstrapTable`? thanks

**Comment by ofirgeller** [comment]
@AllenFang No worries , I appreciate the reply.

I'l try to explain the setup.

When a page loads or the location  of a loaded page changes I make a query according to the location
for example, a user lands following a url like this www.site.com/houses?area=mytown&page=2

At this stage the component containing the table is rendered, and so is the table, I need to sync the state of the table to the state I keep in the URL (the URL is the source of truth), later when the user uses the table controls I will again update the URL.

Example:

```
    // OrderBy and Order
    if (params.has('orderBy')) {
        this.refs.table['handleSort'](params.get('order') || 'asc', params.get('orderBy'));
    }
```

I have no problems in setting the values of any column filters and column sorts, but pagination has a different API, it expects the page and page size to be inside the table options object. this works but is not consistent.

```
        // Not going to work: this.refs.table['handlePaginationData'](page, pageSize);
        // so i do this:
        this.tableOptions.page = parseInt(params.get('page')) || 1;
        this.tableOptions.sizePerPage = parseInt(params.get('pageSize')) || 
        this.tableOptions.sizePerPageList[0];
 
```

It also seems unclear if the table is going to update when you change these properties.
I would like it if calling 'handlePaginationData' when the table is set as remote (and it is) would work even on an empty table (it does not last time I tested).

**Comment by AllenFang** [comment]
HI @ofirgeller, sorry for lately reply, if you enable the `remote` on `BootstrapTable`(Seems like you did), I have some suggestion for your case,

In the remote mode, I expect the developer to handle all the data change(like sort, search, filter, paging, etc) in your mode(Like redux reducer or flux store etc) instead of by BootstrapTable itself. so I usually do not encourage developer to call those exposed API(like `handlerSort`, `handlePaginationData` etc). In remote mode, a BootstrapTable is like a pure and stateless component, only perform the data.

In you case, when your url change with some params, you can change some state in your model then render table again, it's a much a good way in `react.`

For the pagination, I suggest you configure `options.page` and `options. sizePerPage`, please check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-paging.js#L13-L16)

For a advance usage, most of developer said they hope in the remote mode, `react-bootstrap-table` can handle sort, filter, search internally but for the pagination, insert, delete, update, they want to handle by themself, because those operation may have some operation with backend and database, so `react-bootstrap-talbe` also support you to configure `remote` to choose what functionality need to be handled by `react-bootstrap-table`, please check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-alternative.js#L9-L15).

Anyway, I encourage you, in the remote mode, handle the sort or filter by `react-bootstrap-table` itself but handle the pagination by yourself(remote). I think I can achieve your purpose without any `handleSort` or `handlePaginationData` call I guess.

Maybe you can share your example or small repo but please **keep it simple and minimal(**<<It's important), I can help you to refine your code. but need some time lol,  thanks.

Feel free to discuss with me.

**Comment by ofirgeller** [comment]
I am handling the data myself, that's not the problem. 

the table has internal state in the form of buttons for pagination and input boxes for filtering, they are the thing that I need to set to a value that matches the url.

When I know I am on the 2nd page (from thr URL) I need to tell that to the table. I don't expect the table to do anything except for showing the correct pagination buttons. that's all.

The API for doing that is inconsistent. it works one way for filters and in a different way for pagination.

So my problem is different from what you seem to have understood.

**Comment by AllenFang** [comment]
HI @ofirgeller, I think a quick repo for me will be easy to understand your problem, sorry.
