### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by kwolford3** [AllenFang/react-bootstrap-table#1452]
Hey,

Couple quick questions. I'm pretty new to React and web design in general, and I've tried to research it, but I'm still not entirely sure how to go about this. 

1. Is there a way to change the background color of the pagination buttons?
2. For remote pagination, it looks like you still pull and store all of the rows, but only render a portion. Is this correct and if so, is there a way to do it so it only stores the rows that are displayed?

Sorry for the simplicity of the questions, but any help would be appreciated. Thanks in advance.

**Comment by AllenFang** [comment]
@kwolford3, sorry for lately reply, 

1. sorry, we dont have a good way to custom each button for pagination button, we only have some way to custom sizePerPage and whole the pagination panel.
2. In the example, I just want to perform the functionality for remote with pagination, in real case, you still can did it, for example, when page change `options.onPageChange`, you can call a api to fetch the new data and update your state.

It's a question for your case, feel free to discuss with me, thanks

**Comment by kwolford3** [comment]
Thanks for the response. No worries on the button color, but for the pagination, that was my initial thought. However, my concern is that because I'm only making small queries, it won't know how many total entries there are so it won't know the total number of pages/rows. Is this a correct assumption?

**Comment by kwolford3** [comment]
@AllenFang

**Comment by AllenFang** [comment]
@kwolford3, yes, I know your concern, but for `react-bootstrap-table`, we should know the count of total pages so that we can render the pagination list, which means we dont support the infinite paging.

**Comment by kwolford3** [comment]
@AllenFang right. That's what I was thinking. I just wanted to make sure. Thanks for your help

**Comment by nsh87** [comment]
@AllenFang there doesn't seem to be support for *providing* the total page count as a simple integer in the options. it seems that you must give `react-bootstrap-table` the full list of items so it can determine how many buttons to display, but with a large dataset i don't want to do that. i need to be able to give in the options something like `numPages: 52` so users can click to the second page and then at that point i'll fetch the 2nd page via API and `options.onPageChange`. right now i only have a button for 1 page since i download just one page at a time. am i missing something in the options? i tried `paginationSize: 52`, for example, but i only still have 1 button (screenshot).

<img width="653" alt="screen shot 2017-09-29 at 3 31 21 pm" src="https://user-images.githubusercontent.com/4327717/31038373-4a90331a-a52b-11e7-85e1-691478c32617.png">

**Comment by nsh87** [comment]
i see now, [this example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/remote/remote-paging.js#L11-L12
) shows you have to use `remote` at the very least.
```javascript
      <BootstrapTable data={ this.props.data } remote={ true } pagination={ true }
                      fetchInfo={ { dataTotalSize: this.props.totalDataSize } }
                      options={ { sizePerPage: this.props.sizePerPage,
     ...
```
