### ISSUE TITLE
Make rows of table droppable

### ISSUE THREAD

**Issue by ApurvaB** [AllenFang/react-bootstrap-table#1472]
Hi , I am using react dnd with react-bootstrap table.I want to drag a component say a card and drop it on a row of the table.I have reached to the point where I can make table droppable, But I want to make single row droppable.How can I get reference of single row? Or make a behave as a compoenent and make it droppable?

**Comment by AllenFang** [comment]
Hello @ApurvaB, this issue was opened before and currently I haven't no plan to make `react-bootstrap-table` to be droppable or draggable. I guess I need to change code base hugely and I'm also not very familiar with `react-dnd`, so I may not support this feature in future. sorry about that. But PR is welcome if you have good solution on it, thanks
