### ISSUE TITLE
Export additional data aside from the Table Data. CSV Export.

### ISSUE THREAD

**Issue by christianbalderrama** [AllenFang/react-bootstrap-table#1488]
Hi I just want to ask if its possible, but one of the requirement of the export CSV function in my app is to export the CSV with the whole collection not only in the table. So the scenario is that I have some data in the table plus I have data inside the database that is related to that and I want it to be exported as CSV as whole. Cheers.

**Comment by AllenFang** [comment]
@christianbalderrama sorry we dont support this kind of feature, PR is welcome.

Anyway, we have `onExportToCSV` callback and you can return the data you want to export instead of table data, but this callback only support synchronize, so it seems like can't match your requirement, because you data is in the backend and need a async operation to fetch the data.
