### ISSUE TITLE
Selectfilter doesn't work correctly

### ISSUE THREAD

**Issue by CroniD** [AllenFang/react-bootstrap-table#1544]
Hi there,

if one uses a select filter as you suggest in https://allenfang.github.io/react-bootstrap-table/docs.html#filter it won't work as expected if one uses more than 10 key-value pairs (with numbers as keys) in the options object.

I wrote a litte demo here: https://github.com/CroniD/react-bootstrap-table-big/tree/selectfilterbug (code is on branch `selectfilterbug`))

There you can see, if you select `1` it'll match two rows with the value `1` and one row with `10`. It seems you using `include` or `indexOf` or something similiar to match the cell values, which isn't correct for a select action. Instead you should rely on direct comparisions by [Loose equality using ==](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness).

Best regards

**Comment by CroniD** [comment]
I think the mistake is in https://github.com/AllenFang/react-bootstrap-table/blob/master/src/store/TableDataStore.js#L536. The docs mention `eq` as default, but in fact it may be `like`.

**Comment by AllenFang** [comment]
@CroniD yes, the search and filters in the `react-bootstrap-table` are use like to find the data, except for date and number filter, because they can be filter in a range.

if you want to select filter to use eq condition, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/select-filter-with-eq-condition.js#L34) and let me know if you have any questions, thanks you

**Comment by CroniD** [comment]
@AllenFang Okay, thank you. But you should change the docs. http://allenfang.github.io/react-bootstrap-table/docs.html#filter mention `eq` as default for `condition`, which is misleading.
