### ISSUE TITLE
Delete button return something another cell not the isKey={true} one

### ISSUE THREAD

**Issue by BdDragos** [AllenFang/react-bootstrap-table#1548]
I am trying to implement a delete button on my table, and I need to get the value of the entire row or one of its cells so I can return it to one of my POST methods. The problem is that the delete hook returns me the cell which was set as 'isKey={true}', and that's not the cell I need. I tried to set the cell I need with isKey={true}, but then I encounter another problem which is that I cannot insert a row with the isKey={true} cell empty.

How can I either return another cell value using the delete hook, not the one I set as isKey, or to make the insert possible without assigning any value to the isKey cell? Thank you.

**Comment by AllenFang** [comment]
`isKey` on `TableHeaderColumn` or `keyField` on `BootstrapTable` is tell `react-bootstrap-table` which field is key/id, `react-bootstrap-table` will use it to delete or check existing etc.

Back to your question, what hook you used? Because `options.onDeleteRow` and `options.afterDeleteRow` have same arguments, first is key value, the second is the row data.
