### ISSUE TITLE
Unable to write a jest test case rendered by shallow 

### ISSUE THREAD

**Issue by jani937** [AllenFang/react-bootstrap-table#1598]
Anyone has any solution how can i write a Jest test case to check below?
1. whether the row is selected or not and how to simulate a row
2. assume, designed a customFilter on one of the columns and check whether the filter is enabled on a column or not. And, how to simulate the filter text box so that should check the table values.
3. assume i have a delete button, how to write a test case around it?

    getCustomFilter = filterHandler => {
        return (
                `<SearchField
                    key="searchField"
                    id="searchField"
                    ref='search'
                    className='search-field'
                    placeholder='Search'
                    onChange={this.dataSelected.bind(this, filterHandler)}></SearchField>`
        );
    };

    dataSelected = (filterHandler, e) => {
        filterHandler(e.target.value)
    };

`<BootstrapTable id="Table" data={DataSource}
                                hover striped bordered={ false }
                                withoutTabIndex>
            <TableHeaderColumn isKey dataField="Name" dataSort
                               filter={{ type: 'CustomFilter', getElement: this.getCustomFilter.bind(this) }}>
            </TableHeaderColumn>
</BootstrapTable>);`

**Comment by AllenFang** [comment]
HI @jani937 sorry for lately reply

I know there're a lots of thing I need to improve so that I already decide to make a new repo to rebuild `react-bootstrap-table`: https://github.com/react-bootstrap-table/react-bootstrap-table2

Anyway, something is hard to test as I know, so not sure if following answer can help you
1. just check the checkbox directly or check the state of `react-bootstrap-table`, because the select row key will saved in the state as `selectedRowKeys`

2. If you have a column filter, I think your test case should focus on itself. if you just wanna check if the filter appear on the specified header, just check the DOMNode or something

3. Same as above, each custom component should have itself tests, even some callback function, you can still verify a callback whether being called. Use `sinon` is a good point to test it
