### ISSUE TITLE
custom export csv folder location

### ISSUE THREAD

**Issue by narendravenkata** [AllenFang/react-bootstrap-table#1617]
Is there a way to provide the destination folder for the csv to be exported using export csv option.

**Comment by AllenFang** [comment]
I'm not sure whether we can control the download path via `blob`, but this feature is also minor to me, I think I'll not support this feature in near future, but PR is welcome 👍

**Comment by ananthshenoy** [comment]
Hi @AllenFang. I am using react-bootstrap-table in a project and I need the above mentioned feature in the table. So I am interested to work on this. We can add this feature later on to react-bootstrap-table2 as well.

**Comment by AllenFang** [comment]
@ananthshenoy  PR is welcome for `react-bootstrap-table`, thanks

**Comment by ananthshenoy** [comment]
Hi @AllenFang. I spent some time to look if there is a way to give destination folder for csv to be exported and found that this cannot be done using JS(Reference: https://github.com/eligrey/FileSaver.js/issues/42) due to security restrictions in File API.
We can achieve this by changing the browser settings as shown in https://www.lifewire.com/change-the-file-download-location-4046428. 
So I guess this issue can be closed.

**Comment by AllenFang** [comment]
@ananthshenoy Nice sharing :)  thank you~
