### ISSUE TITLE
onRowSelect and onSelectAll not checking checkbox

### ISSUE THREAD

**Issue by MichielDx** [AllenFang/react-bootstrap-table#1656]
I have this code: 

[GitHub code doesn't format correctly](https://pastebin.com/U1BeigGY)

If I remove the setState on either of them, the checkboxes will be checked.

Is there something I have to do to prevent this?

**Comment by AllenFang** [comment]
@MichielDx what is `updateList` ?

**Comment by MichielDx** [comment]
The rows that are selected will get updated when the user clicks a button. So `updateList` is the list with selected rows.

**Comment by AllenFang** [comment]
@MichielDx some questions, when you use `state.updateList`??

if you want to control the selection rows by your `state`, the `state.updateList` should be an array which contains only rowkeys and pass this state(`state.updateList`) to `selectRow.selected` props.

It's sorry because I didn't have any idea about what your purpose, I can help you if you give more details about your code and explain it. thanks

following is an example if you want to control the selection by your `state`.
https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/selection/externally-managed-selection.js
