### ISSUE TITLE
TextFilter by few fields

### ISSUE THREAD

**Issue by foreveRush** [AllenFang/react-bootstrap-table#1679]
Hi, I have some problem with filtering.
My data looks like:
```
[
 {
  playerName: "Bob",
  Timestamp: "2016-12-15T18:01:26Z",
  sensorActionId: "JUMP"
 },
...
 {
  playerName: "Alice",
  Timestamp: "2016-12-15T18:05:26Z",
  actionId: "IN"
 },
]
```
I need to show 3 columns: Player name, time and action (here could be actionId or sensorActionId). I can't change data.

So, to show these data I use next solution:
```
actionChecker(cell, row) {
        return cell ? cell : row['sensorActionId'];
    }

<TableHeaderColumn
                        dataField='actionId' width={'60px'} dataSort={ true }
                        dataAlign='center' filter={ {type: 'TextFilter', delay: 200} }
                        dataFormat={this.actionChecker}
                    >
```

All is ok, I see all actions, but when I try to filter them, table filter just by `'actionId'` field. How can I tell table to check equals for `'actionId'` OR `'sensorActionId'`?

I don't want to use CustomFilter because I don't need my custom react element.

Thanks.

**Comment by AllenFang** [comment]
The `filterFormatted` is most easy way to do it, `react-bootstrap-table` will filter the formatted data instead of raw data.

But if your formatting return a HTML or React JSX, `filterFormatted` will be not good solution, but we still support `filterValue`

`filterValue` accept a callback function like `dataFormat` and give `cell` and `row` as argument, in your callback, you can decide what kind of data you want to be filtering or search

`filterFormatted` and `filterValue` are the props on `TableHeaderColumn`,

check following example to learn

https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/search-format-table.js

Thanks and let me know if you have any other question,.
