### ISSUE TITLE
When remote is set to true a sorted table is reset to default sort when a state update is performed in the application.

### ISSUE THREAD

**Issue by widdde** [AllenFang/react-bootstrap-table#1702]
Similar to an earlier issue I added a bug report about, sorted table will get back to a default sorting order when a state update happens in the application. This issue is similar to the search issue, when a search result was reset after a state update in the application.
I have remote set to this.remote which point to a method that sets certain operations to remote on RemoteObject.

**Comment by welchn** [comment]
I am seeing this issue as well...I have remote filtering enabled, but still want to use local sorting.  I specify this like:
<BootstrapTable ref='table' filter remote={remoteMode}...
And the remoteMode function is this:
function remoteMode(remoteObj) {
     remoteObj.filter = true;
     return remoteObj;
}

Everything works fine...remote filtering works, local sorting works, but if a state change occurs, such as selecting a table row, the sort order reverts back to the default.

The root cause seems to be in bootstrap-table's "ComponentWillReceiveProps" function.  The code looks like this:
if (this.isRemoteDataSource()) {
          var data = nextProps.data.slice();
          if (nextProps.pagination && !this.allowRemote(_Const2.default.REMOTE_PAGE)) {
            data = this.store.page(page, sizePerPage).get();
          }
          this.setState(function () {
            return {
              data: data,
              currPage: page,
              sizePerPage: sizePerPage,
              reset: false
            };
          });
        } else {       
         // #125
          // remove !options.page for #709
          if (page > Math.ceil(nextProps.data.length / sizePerPage)) {
            page = 1;
          }
          var sortList = this.store.getSortInfo();
          var sortField = options.sortName;
          var sortOrder = options.sortOrder;
          if (sortField && sortOrder) {
            this.store.setSortInfo(sortOrder, sortField);
            this.store.sort();
          } else if (sortList.length > 0) {
            this.store.sort();
          }
etc.
The call to this.isRemoteDataSource() will return true if "any" remote operations are enabled.  My only remote operation is filtering.  I still want the local sorting behavior, so I want the "else" clause to execute here, not the "if" clause.  I think instead of calling "this.isRemoteDataSource()", the function instead called "this.allowRemote(_Const2.default.REMOTE_SORT)", I would get the desired behavior.

Allen, is this a potential bug in the bootstrap-table code?  Or am I doing something wrong here?
Thanks!
Nancy

**Comment by widdde** [comment]
All my issues starts when I activate remote on the react bootstrap table. If i disable remote everything works as expected, and I can still "remote edit and remote insert data" by define which method to handle, for example, a cell edit.
By defining onCellEdit, onDeleteRow, onAddrow I can still do updates, inserts and deletes "remote".
What benefit do I get to actually activate remote={this.remote} ? 
From the beginning I thought that I wasn't able to "override" onAddrow, onDeleteRow or onCellEdit if remote was set to false, but that is not true.. 
I can still do whatever I want in those methods and they are called when updating, deleting or adding data to the table..

**Comment by AllenFang** [comment]
hi guys, sorry for lately reply...

I'm still trying to reproduce this issue, but just want to clear the air.

1. the prerequest is that you enable the `remote` **only** for filter/search
2. you sorting a field
3. then search/filtering the table
4. you observe the sorting is not correct? Am I right?

Thanks

**Comment by welchn** [comment]
Hi Allen, thank you for the reply!  So, steps to reproduce the issue:
1) enable remote **only** for filter/search
2) Sort a field by clicking on the column
3) Trigger any subsequent state change (selecting a row will work, or maybe add a handler using options.onRowMouseOver to trigger an event)

When the state change happens, the sorting reverts back to the default sort, instead of the sort you deliberately chose in step (2) above.

Please let me know if this is not clear.
Thanks!
Nancy

**Comment by AllenFang** [comment]
hey guy, update to `v4.1.1` and check it again, thanks

**Comment by welchn** [comment]
Initial tests look good!  Will test more later.  Thank you so much, Allen!
