### ISSUE TITLE
Highlight change of data

### ISSUE THREAD

**Issue by Reastyn** [AllenFang/react-bootstrap-table#171]
Hi,
I'd to highlight row with updated data. One column changed -> row will have class changed.
Is that somehow possible?
Thanks for awesome lib

**Comment by AllenFang** [comment]
@Reastyn, what cause the **updated data**, cell editing or your re-render?

**Comment by Reastyn** [comment]
I re-render with TableDataSet. I just got an idea that I would make property in json (isUpdated) and then check it with trClassName. Do you have better solution?

**Comment by AllenFang** [comment]
@Reastyn, if you update data with cell editing, I can help you to achieve requirement, but it's not. Anyway, you solution is best one, because if I want to make the deference between two data set, I must cache it and compare it, so I thinks this action should be done on your program. However, your solution should be better

**Comment by Reastyn** [comment]
OK! Thank you helping and awesome library!
