### ISSUE TITLE
[Help] btngroup w/ search, new and refresh glyphicon all in one row

### ISSUE THREAD

**Issue by sacredMonster** [AllenFang/react-bootstrap-table#1721]
Hello,
How can I add a new , search bar and refresh glyph-icon all under a btn group in one row? Right now, the new button and the search bar are added in columns.
thanks!!

**Comment by AllenFang** [comment]
Maybe you can check this example: https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/custom/toolbar/custom-toolbar-1.js

I know there's a lot of enhancement I can do in `react-bootstrap-table`. But we have some bad design from the beginning. That's why I decide to implement [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2), but it's still work in progress.  Let me know if you have any question, thanks
