### ISSUE TITLE
Unexpected keyBoardNav in case column with duplicated "dataField" values

### ISSUE THREAD

**Issue by bigunaleksej** [AllenFang/react-bootstrap-table#1756]
**Description**
We have data 
```
[
{
    title: 'somevalue',
    desciption: 'somevalue',
    price: 'somevalue',
  }
]
```
and for exampe we want create table with 4 columns where we want display "price" for differend currencies. So when we create 2 columns with dataField 'price' and enable keyBoardNav we can't move for 4-th column by keyboard.

**Example**
https://codepen.io/anon/pen/jaLQve

**Comment by AllenFang** [comment]
@bigunaleksej this is a known issue, `react-bootstrap-table` use `dataField` as unique key to find all the columns. Which means we are not encourage people to use same column in a table. This problems will be fixed in [`react-bootstrap-table2`](https://github.com/react-bootstrap-table/react-bootstrap-table2/tree/develop).

Sorry about that, I'll recommend to predfined 4th column for different currencies. Let me know if you have any questions, thank
