### ISSUE TITLE
blurToSave breaks tabbing between fields

### ISSUE THREAD

**Issue by craigles** [AllenFang/react-bootstrap-table#1780]
When blurToSave is set to true, I am no longer able to tab between editable fields. When I hit tab it doesn't go anywhere:

![blurtosave](https://user-images.githubusercontent.com/1442491/33355950-7eeb79b2-d505-11e7-8bb4-5ba456a8f2d3.gif)

This is using the markup from your Blur to Save example:
```
const cellEditProp = {
  mode: 'click',
  blurToSave: true
};

class BlurToSaveTable extends React.Component {
  render() {
    return (
      <BootstrapTable data={ products } cellEdit={ cellEditProp }>
          <TableHeaderColumn dataField='id' isKey>Product ID</TableHeaderColumn>
          <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
          <TableHeaderColumn dataField='price'>Product Price</TableHeaderColumn>
      </BootstrapTable>
    );
  }
}
```
I'd expect to be able to click outside of the cell to save as well as have the functionality to tab out and save cells.

The functionality seems to work fine on the doco site though :\

Thanks for your great work :)

**Comment by AllenFang** [comment]
@craigles sorry for lately reply, about your concern, in the first design for integrate with cell edit and keyboard nav, when keydown `tab` and only fire `blur` event and ignore the `tab` event, because there're some wired issues. That's said: blur have higher priority than tab when you are editing the cell(mouse focusin the input field)

Anyway, PR is welcome
