### ISSUE TITLE
Use a custom sort when sorting externally?

### ISSUE THREAD

**Issue by rikkirabz** [AllenFang/react-bootstrap-table#1841]
Hi! In the sort-table.js example we are able to call handle sort externally but here we are only calling the default sort method: 
```

  handleBtnClick = () => {
    if (order === 'desc') {
      this.refs.table.handleSort('asc', 'name');
      order = 'asc';
    } else {
      this.refs.table.handleSort('desc', 'name');
      order = 'desc';
    }
  }
```

Is there a way to call our own custom sort that we have defined and if so which parameters are we supposed to pass in when we only have the order and datafield?  Any help would be greatly appreciated! 

Here we are passing 3 parameters where as in the default sort we are only passing 2...
```
function revertSortFunc(a, b, order) {   // order is desc or asc
  if (order === 'desc') {
    return a.price - b.price;
  } else {
    return b.price - a.price;
  }
}
```

**Comment by AllenFang** [comment]
HI @rikkirabz, `sort-table.js` is just an example to perform the sorting by your application or other user action instead of clicking the header column. Actually, this example still doing the sorting internally(`react-bootstrap-table`)

In your case, if you want to use your custom sort function, I will not suggest you to use the example of `sort-table.js`, you are suppose to use `sortFunc` on `TableHeaderColumn`

Hope I answer you question because I still not very clean to your question a little bit.
