### ISSUE TITLE
layout

### ISSUE THREAD

**Issue by shorif2000** [AllenFang/react-bootstrap-table#1895]
Is it possible to move the layout of the elements around? 

i would like to place the sizeperpage dropdown list on the top left hand side. jquery-datatables had a nice way of doing this, all my existing tables are done by [datatables.net](http://datatables.net). i am trying to make it look similar.

also 
- is there any feature that displays no. of rows found in table and if any is filtered?

**Comment by AllenFang** [comment]
@shorif2000 for the sizePerPage layout, you can consider to use [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/pagination/custom-pagination-table.js#L54) but actually, it's hard to custom each component right now in `react-bootstrap-table`, that's why I want to create [`react-bootstrap-table2`](https://react-bootstrap-table.github.io/react-bootstrap-table2/)

> is there any feature that displays no. of rows found in table and if any is filtered?
No

**Comment by shorif2000** [comment]
i did a little hack

```
moveElement() {
	  //store a this ref, and
	  var _this = this;
	  //wait for a paint to do scrolly stuff
	  window.requestAnimationFrame(function() {
		  if($(".react-bs-table-tool-bar").length > 0){
			  if($(".react-bs-table-tool-bar .react-bs-table-sizePerPage-dropdown").length <= 0){

				  $(".react-bs-table-sizePerPage-dropdown").prependTo(".react-bs-table-tool-bar");
			  }
		  }
	  });
	}
```


and then in render

```
render() {
        let table = <div>Loading...<i className="fa fa-spinner fa-spin"></i></div>;
        if ( Object.keys(this.props.reportsWorkerJobs).length > 0) {
            table = this.renderTable(this.state.data);
            this.moveElement();
        }
```

this moves it on top of the button group
