### ISSUE TITLE
Is there a simple way of showing only selected rows?

### ISSUE THREAD

**Issue by vgoklani** [AllenFang/react-bootstrap-table#207]
Hi - I'm wondering if there is a simple toggle for showing only selected rows

Thanks

**Comment by AllenFang** [comment]
@vgoklani, you means default selected on table? Why I ask, because if the table rendered at first time then I select a row, if I enable "showing only selected rows", will cause user can't select another anymore...

if another question, welcome to join the [gitter](https://gitter.im/AllenFang/react-bootstrap-table) to discuss with us.

**Comment by vgoklani** [comment]
For my use case, I have >1500 rows, and the user will select maybe 50.
the problem is that there isn't a simple way to see only the selected rows.

**Comment by AllenFang** [comment]
ok, I can add a button on top of table, if user click, then showing only selected rows, how about this idea?

**Comment by vgoklani** [comment]
sounds good, thanks!

**Comment by AllenFang** [comment]
@vgoklani, for now, the workaround is you can handle selected row outside of the ```react-bootstrap-table``` and add a button in your component, when user clicked, you can just rendered these selected rows on table :)

**Comment by AllenFang** [comment]
@vgoklani, check the ```v1.4.2``` for fixing. It's an example.[939d53b](https://github.com/AllenFang/react-bootstrap-table/commit/939d53b7c460644811d2a5dfd034d4da3fddeb57)

add  ```showOnlySelected``` on ```selectRow``` props
```js
var selectRowProp = {
    mode: "checkbox",
    showOnlySelected: true
};
```
