### ISSUE TITLE
Checkbox checked property still remainig even if I reassgined data

### ISSUE THREAD

**Issue by Dhaval8087** [AllenFang/react-bootstrap-table#244]
I have two tab and in both tab I have used the react-bootstrap-table so on very first tab I have selected 2 record usig check box and going to second tab and select one record and came back to first tab it will show 2 record selected even if I have reassigned data when tab is clicked how can I set all deselect when change tab and coming back

**Comment by AllenFang** [comment]
@Dhaval8087, do you want the table clean all selection states when switching tab?

**Comment by Dhaval8087** [comment]
Yes it should not maintain the state when I switch to other tab currently it maintain the state

**Comment by AllenFang** [comment]
The selection state should be maintain inside even if you reload the data. Because I never know the state outside of this component. So, there are some solution for you: 
1. when you change tab, you can set the default selected as empty for cleaning table selection.  
2. I can provide a expose API function for user to clean the selection state as their desired

I thinks the second one is a better solution, if you confirm this, I can add it in next version
Thanks

**Comment by Dhaval8087** [comment]
Yes, Please it would be really great help if you can update in react-bootstrap-table API so user can clean the select state wherever he wants :) its really appreciate your quick response I am waiting for next version 
Thanks

**Comment by AllenFang** [comment]
```js
// clean all selection as following
this.refs.table.cleanSelected()

//...
<BootstrapTable ref='table' ...>
...
</BootstrapTable>

```
Supported on v1.4.6
