### ISSUE TITLE
Option to move pagination to the top

### ISSUE THREAD

**Issue by jochenberger** [AllenFang/react-bootstrap-table#275]
I'd like to be able to render the pagination above the table instead of below.

**Comment by AllenFang** [comment]
@jochenberger, I dont want to make this as an optional, sorry. But you can customize one based on ```react-bootstrap-table```

**Comment by jochenberger** [comment]
It's alright if you don't want to support it. If you just don't want to spend any time on it, I can as well create a PR.

**Comment by AllenFang** [comment]
sure, there are some important issues need to fix, sorry

**Comment by jochenberger** [comment]
Okay, would you like a PR or don't you want that feature anyway?

**Comment by AllenFang** [comment]
@jochenberger, I have no idea, you can open a PR for this feature. Before opening PR, I think you need to tell me where the pagination be moved(on top of toolbar or below?) and make sure this feature more configurable. btw, because there are a lots of changing in my new plan for fixing table structure and column width problem, so I think wait me to release this change is better for you. :)
