### ISSUE TITLE
origin column filter broken after v1.5.1

### ISSUE THREAD

**Issue by AllenFang** [AllenFang/react-bootstrap-table#293]
self-explanatory

**Comment by dana2208** [comment]
Hello @AllenFang ,

I did a quick fix before you merged my pull request in v.1.5.1 so that it supports the old filtering.
But it seems I was not quick enough since I saw now it is not part of v.1.5.1.

You can see in [here] (https://github.com/dana2208/react-bootstrap-table/commit/3cb6f7002c73ddf7c1a82c0313371110751fb29f#diff-29) that TableDataStore.js contain the following code that is not in your own version (lines 208 to 211):
`// support old filter`
 `              if (filterVal === undefined) {`
`                filterVal = filterObj[key].toLowerCase();`
 `              }`
This way the old filtering way is not broken.

I can make a new PR with these 4 lines if you want.
Let me know.

Thanks

**Comment by AllenFang** [comment]
if your solution is work for both origin and new column filter, just open a PR :0
Thanks !

**Comment by dana2208** [comment]
My PR: support old filter #296

Thanks!

**Comment by AllenFang** [comment]
Thanks your contribution, I've merge and released on v1.5.3
