### ISSUE TITLE
Separate search panel to exclude items 

### ISSUE THREAD

**Issue by opensourcegeek** [AllenFang/react-bootstrap-table#305]
I was wondering if anyone tried to do an exclusion search with this component. I'd like to add an inclusion search and an exclusion search, so that if any row contains this exclusion text it will be removed in the result. So for eg.

if following are the rows in my data
 A B C D E
 B C D E F

columns are separated by space, then an inclusion search (this functionality is already there) for A will get the first row. If after that E is added to exclusion search then the first row will be removed from result. Will this functionality be useful for others, has anyone tried implementing it?

**Comment by AllenFang** [comment]
@opensourcegeek, I think this feature is ok, but I wont fix this issues actively. Because there are some issues need to doIn addition. In addition,  I think this feature can be done on your component, I mean you can control this exclude search and manage state on your component., so PR welcome but please don't make old search functionality broken.
