### ISSUE TITLE
Is it possible to create a column on the fly and also make it part of CSV export?

### ISSUE THREAD

**Issue by opensourcegeek** [AllenFang/react-bootstrap-table#313]
I have some columns and I need to derive a new column from existing columns. I cannot at the moment create new column if it's not already in the array of objects. I also need that column in CSV export - is this possible?

**Comment by AllenFang** [comment]
@opensourcegeek, i think it is possible and this issue seems like "add new column dynamically". I've tried it at a long time ago, but there are some issues like width cant be adjusted properly .etc. I thinks it can be done but the priority is very lower and the workaround is manage the columns state on your component, I means control "add new column dynamically" on you component, just tell ```react-bootstrap-table``` what columns it should be rendered. So I want to close this issue currently, but not means I dont want to fix it, if I try it successful in the future, I will make this as a new feature.

if you have any question on this issues, we can discuss more, may be you can tell me your case and I can help you :)

**Comment by annelorraineuy** [comment]
My problem could be similar, I think. I was wondering if it is possible to include the hidden columns upon exporting to CSV?

**Comment by AllenFang** [comment]
@aaronhayes, Your requirement is easy to do, I can support a options props to let you decide if the hidden should be included in csv.

**Comment by annelorraineuy** [comment]
That would be awesome! 

Anne Lorraine Uy
www.anneuy.com

**Comment by AllenFang** [comment]
@annelorraineuy, released on ```v2.3.8``` and check [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/manipulation/export-csv-column-table.js#L40)
