### ISSUE TITLE
Is there a way to add a single line?

### ISSUE THREAD

**Issue by alexmngn** [AllenFang/react-bootstrap-table#395]
Hi,
As I am fetching my data over the network before displaying it in the table, I would like to add a line in the table with a spinner in the meantime (colspan=numberOfColumns)
Is there a way to do that?
Thanks

**Comment by AllenFang** [comment]
HI @alexmngn, I'm sorry that there's no way to do it ;(

**Comment by AllenFang** [comment]
HI @alexmngn again. I am not sure you scenario, but I thinks you just want to add a spinner in table when there's no any data in there, because you're fetching data. So ```react-bootstrap-table``` support ```noDataText``` to user to customize the text when data is empty. In #374, also support ```noDataText``` accept a JSX so that user have more ability to customize.  So maybe you can thinks this solution like following:

```js
var options = {
  noDataText: ( <select>......</select> );
};
``` 

Thanks
