### ISSUE TITLE
What needs to be done to be bootstrap independant?

### ISSUE THREAD

**Issue by squaredonut** [AllenFang/react-bootstrap-table#431]
So i know this counter the name of the plugin, but because I'm making a google chrome extension and an injected bootstrap.css kind of clashes with the styles.

I've tried to fork and postfix/wrap the boostrap styles and that only partially fixes it, but messes up a lot of the grid's layout.

Amongst all the react table components, this one is the cleanest and complete to use. 

Is there anyway to know which bits to abstract or supply classes for so i dont need to use bootstrap?

Thanks!

**Comment by AllenFang** [comment]
hi @squaredonut, i'm not very surly for your requirement, but it seems like impossible, because if you dont use bootstrap styling, I thinks this component will crash, I mean I dont know what happened on it.

So, sorry about that, but i think you can try to find some tool which can transfer the outside css file into react inline styling, maybe it's your answer. :0
