### ISSUE TITLE
Pagination should use react-bootstrap

### ISSUE THREAD

**Issue by sgentile** [AllenFang/react-bootstrap-table#434]
Looking at this issue:
https://github.com/AllenFang/react-bootstrap-table/issues/338

I believe if that pagination was written with react-bootstrap it would eliminate the need for the bootstrap.js (and even better, jQuery).

imo - this component since it uses react-bootstrap should use it and not depend on the bootstrap.js file separately

**Comment by mkozhukharenko** [comment]
+1! Why on earth the bootstrap.js must be included to a projec to make a dropdown (from a pagination module) work?

**Comment by AllenFang** [comment]
hey guys, thanks your suggestion. At the beginning of this project, I also thinks about a dependency on ```react-bootstrap```. But I thinks it's not necessary really and if it depends, there will be a lots of dependency problems. so I just want to isolate it and let user to handle ```bootstrap```. 

But to now, I feel the same pain on the depends of ```bootstrap.js```, so this issue has been created on #197 and #232 has tried to fix it.

Anyway, because something missing so I revert #232, and hope I can fix this issues in near future. So I just close this issues and please follow up #197 

Thank you guys :)
