### ISSUE TITLE
Material-Ui version

### ISSUE THREAD

**Issue by Umar-Abbas** [AllenFang/react-bootstrap-table#455]
Hi buddy!
thanks for such a great package. we already using this package in our projects. we are going to start a new project based on Material-ui. Do you have any future plan to customize react-bootstrap-table for material-Ui?

Thanks

**Comment by AllenFang** [comment]
HI, @Umar-Abbas, that's glad to hear there's a implementation for material version 👍  For the future plan, I thinks you can follow the issues and there are some feature  is very valuable, ex: nest data, column toggle, sub-tree in row(expandable) etc. BTW, I've some advices for you, but I cant remember them currently, but for example, like #409, it's a mistake which I controller some component inside so that lose the ability customization.  Just feel free to discuss with me.
