### ISSUE TITLE
Mouseover the column to see the value if the column width is not wide enough

### ISSUE THREAD

**Issue by simonhsu** [AllenFang/react-bootstrap-table#486]
As the title mentioned,

Take an example, if the column value is **"react-bootstrap-table"**
The table now will show the **"react-boots..."**  if the column width is not wide enough.
And there's no way to see the entire value in the front-end side.

Is there a way to solve that?
Thanks in advance.

**Comment by AllenFang** [comment]
@simonhsu, the better solution is give a fixed width on column currently, however it's not satisfied with all the cases. the other workaround is enable ```columnTitle``` on ```TableHeaderColumn``` which you display all the value on title, but it's not a choice very well, because the user need to hover on that cell at first.

Anyway, I can make the cell to display all the value, but it will broke the column width if it given. so if you can fix this problem I described, PR is welcome 👍

**Comment by gshakir** [comment]
@simonhsu . One way to fix is to apply this CSS and the whole value will display on mouse over.

`
.react-bs-table table td:hover {
    white-space: normal;
    overflow-x: auto;
}

`

**Comment by AllenFang** [comment]
@gshakir, thanks you :)

**Comment by 3-john-4** [comment]
This solution worked a little better for me. On mouse over the td expands vertically to fit the entire value.
```
.react-bs-table table td:hover {
  overflow-wrap: break-word;
  max-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: normal;
}
```

**Comment by simonhsu** [comment]
Thank you all. It works like a charm. close it
