### ISSUE TITLE
sort formated data

### ISSUE THREAD

**Issue by biggu0** [AllenFang/react-bootstrap-table#498]
dear AllenFang:
   when I use numeral format table's data,the sort value  will be chaos.seems like it deal with a string, '210,00.00' will behid '1,111,00.00'

**Comment by AllenFang** [comment]
@biggu0, exactly, if your field value is string, it'll be handled with string, because ```react-bootstrap-table``` didn't support field type, so this issue cant be solved, but you can use ```sortFunc``` to customize your sorting logic so that you can convert the ```210,00.00``` to ```21000```.

I'll close this issue because this wont fix, but feel free to discuss with me :)
thanks.

**Comment by AllenFang** [comment]
BTW, you can give ```formatExtraData``` a try, there's a [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/sort/custom-sort-with-extra-data-table.js), I thinks it's also another solution.
