### ISSUE TITLE
Feature Request: Hook for delete and create

### ISSUE THREAD

**Issue by ryanlinnane** [AllenFang/react-bootstrap-table#53]
I'd like to use this in conjunction with a backend REST API. Is there an easy way to know when a given action has occurred and on what cell so that i can make the appropriate ajax call? I see that EDIT has a hook for this. Furthermore, I love the automated modal for submission, but is there a way to limit the fields that pop up - i.e. ID may often be autogenerated on the server.

**Comment by AllenFang** [comment]
The hook for delete and create row is great, it's a good enhancement for this component. And your are right, the ID field always generated from server, so the ID field need to be not editable. However, I will spend some time to implement these feature. Thanks for your feedback :)

**Comment by AllenFang** [comment]
Hi @magicantler , I've add the hook for delete and create row on table, the example as follow:
<pre>
var options = {
  afterDeleteRow: onAfterDeleteRow,  // A hook for after droping rows.
  afterInsertRow: onAfterInsertRow   // A hook for after insert rows
};
//...
&lt;BootstrapTable data={products} options={options}&gt;
  //...
&lt;/BootstrapTable&gt;
</pre>

And about the field limitation in modal for row creation, I've not yet implement it. Maybe in next version :)

**Comment by AllenFang** [comment]
HI @magicantler , about the field limitation in modal for row creation, I think the <code>editable={false}</code> on <code>TableHeaderColumn</code> is a good idea to achieve. But about the row key field, in my opinion, I want make it editable, because the data cant be store without row key. So if you want to make the key field non-editabled, I prefer you create the new row outside, save it and render <code>react-bootstrap-table</code> again :) Anyway, I'll add the editable field in modal in next version.

**Comment by AllenFang** [comment]
HI @ryanlinnane, in 1.0.0, you can use <code>editable={false}</code> on <code>&lt;TableHeaderColumn&gt;</code> to limit the field in modal. if rowkey, you can use <code>&lt;TableHeaderColumn dataField="id" isKey={true} autoValue={true}&gt;Job ID&lt;/TableHeaderColumn&gt;</code> to make row key can't be input and auto generate a key for unique identify in this component.
