### ISSUE TITLE
Question: How should I generate ID's if my data doesn't have any?

### ISSUE THREAD

**Issue by thevangelist** [AllenFang/react-bootstrap-table#588]
I am wondering is it mandatory to provide isKey parameter? could this be somehow generated for each element directly based on the data in the component instead of having to add custom functions to generate the ID?

**Comment by AllenFang** [comment]
@thevangelist, sorry for lately reply. That's said, the ID is be used on get the unique row for insert, update, delete or search etc. so it's necessary for table. In you case, you can generate ID field by a sequence number or timestamp. BTW, it's better to use ```keyField``` instead of ```isKey```, check following:

```js
<BootstrapTable data={...} keyField='MY_ID'>
</BootstrapTable>
```

or hide ID column if you use ```isKey```

```js
<BootstrapTable data={...}>
    <TableHeaderColumn dataField='MY_ID' isKey hidden>MY_ID</TableHeaderColumn>
    <TableHeaderColumn dataField='name'>Product Name</TableHeaderColumn>
</BootstrapTable>
```

**Comment by thevangelist** [comment]
Thanks! I'll use the hidden flag

**Comment by thevangelist** [comment]
I mapped my array of objects and added an unique key to each of them with https://www.npmjs.com/package/shortid (kept it hidden, as this was kinda the original problem)
