### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop

### ISSUE THREAD

**Issue by laurenamy** [AllenFang/react-bootstrap-table#594]
This might be silly but an array of JSON data throws this warning.

**Comment by madeinfree** [comment]
Hi @laurenamy,
This warn not easily to found out, it happens when use `map` and didn't given `key` props, anyway if you have happened again, you may take a picture here, Thanks ~

**Comment by microdou** [comment]
This warning occurs since  `v 2.3.8`. No warning in `v 2.3.7`. 
``Warning: flattenChildren(...): Encountered two children with the same key, `Abc`. Child keys must be unique; when two children share a key, only the first child will be used.``
`in tbody (created by TableBody)`
`in table (created by TableBody)`
`in div (created by TableBody)`
`in TableBody (created by BootstrapTable)`
`in div (created by BootstrapTable)`
`in div (created by BootstrapTable)`
`in BootstrapTable`

**Comment by madeinfree** [comment]
@microdou Thanks, I'll check it later !

**Comment by AllenFang** [comment]
Sorry for lately reply. Any sample code can reproduce this issue? Thanks :)

**Comment by lmalvaran** [comment]
I have encountered this problem when using array of objects that returns map. The solution I made is to convert it. I'm not sure if this is a good solution, but it works in my case.
`var arrList=[];
objects.map((obj) =>
            {  var a = {
                        prop1 : obj.get("prop1"),
                        prop2 : obj.get("prop3"),
                        n     : obj.get("n")
                    };
                arrList.push(a);
            }
        ); `

**Comment by AllenFang** [comment]
@laurenamy, the snippet you show up is that your solution?

**Comment by microdou** [comment]
@AllenFang 
It appears that now a unique value is somehow required in each object of the data array since `v2.3.8`. This unique value is used to provide a unique Key in Table. When values in a dataField are not unique, error occurs.
My previous data array and TableHeaderColumn:
```
Data = [
    {name:"apple"},
    {name:"orange"},
    {name:"orange"},
]
<BootstrapTable data={Data}>
  <TableHeaderColumn dataField="name" isKey={true}>Name</TableHeaderColumn>
</BootstrapTable>
```
Unique id is added to new data, and is set as key via `isKey={true}`. Error and warnings are now gone.
```
Data = [
    {id: 0, name:"apple"},
    {id: 1, name:"orange"},
    {id: 1, name:"orange"},
]
<BootstrapTable data={Data}>
  <TableHeaderColumn dataField="id" isKey={true}>Name</TableHeaderColumn>
  <TableHeaderColumn dataField="name">Name</TableHeaderColumn>
</BootstrapTable>
```

**Comment by AllenFang** [comment]
@microdou, I got it. Actually, if ```isKey``` been applied, you should ensure the key column should not duplicated. If there's no any unique columns, I suggest you generate a set of sequence number to applied as key column.

**Comment by pypetey** [comment]
Is there a way to use isKey but in the same time not to display a column containing id?
