### ISSUE TITLE
from-to date and time filters

### ISSUE THREAD

**Issue by drakipovic** [AllenFang/react-bootstrap-table#601]
Hi, is it possible to have from-to range filters for dates and times?

Thanks

**Comment by AllenFang** [comment]
I'll pending this feature because release ```v3.0.0``` have the highest priority. BTW, I'm afraid you wait too long for this feature, maybe you can customize one, the filter is able to customize.  Thanks :)

**Comment by drakipovic** [comment]
Can you explain in short how to do it? I read some documentation but I didnt quite get it.

Thanks

**Comment by AllenFang** [comment]
@drakipovic, there's an [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js) you can check. Feel Free to discuss with me. 

I hope you can explore how to write a custom filter by this example, if there're some trouble, please let me know, it may is bug or something need to enhance.

BTW, I event dont try to write a custom filter, because the filter is not design by me. But I actually know there're some people does it.  so ask me anything after studying this example.

Thanks

**Comment by SmashedBird** [comment]
I'm struggling with the same issue. I need to filter using a date range. 
I tried to duplicate the date column, set one filter >= 'from date', and on the duplicated column set a filter <= 'to date' but only the latest entered is being taken into consideration. I don't mind having duplicated columns because I can hide them afterward but I cannot figure out how to apply 2 filters on the same column

**Comment by AllenFang** [comment]
hey @SmashedBird, `react-bootstrap-table` doesn't support the duplicated column, I means have multiple same `dataField` on `TableHeaderColumn`.

if you want a date range, you can custom it in one column. Feel free to discuss with me if I misunderstand something. thanks

**Comment by SmashedBird** [comment]
Thanks for your help @AllenFang ; I tried to create a custom filter but cannot figure it out so far ; I tried a 'Programmatically Date Filter' from the doc, which works perfectly but I didn't find a way to set it up so it can take 2 conditions on a date field [ >= x && <= y for example ]. I would really appreciate if you could help me figure this one out!

**Comment by AllenFang** [comment]
> I tried a 'Programmatically Date Filter' from the doc, which works perfectly but I didn't find a way to set it up so it can take 2 conditions on a date field [ >= x && <= y for example ]

yes, currently we dont support date filter with a range, only support one condition.
For example >= x  but we dont support  >= x && <= y

So I mean here is we dont support the date range filter like your example but you can custom it the filter component by yourself.

You can check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js) to learn how to custom it

Sorry for forgetting to get your an example for learning how to custom filter, but please let me know if you stuck on custom filter, thanks

**Comment by StohlmanMatteo** [comment]
@SmashedBird 
Where you able to create a custom filter for this? I am having the same issue and having trouble wrapping my head around the custom filter example as it applies to a date range filter.

**Comment by rikkirabz** [comment]
Are there any updates on this issue?  I am struggling with this as well.

**Comment by iamanoopmk** [comment]
Did anyone get this one working? Still don't see a way to achieve this.

**Comment by dlplenin** [comment]
If this helps someone....

I found [this](http://jsfiddle.net/oakley808/h07bukjr/), but it doesn't run.

So taking in accoutn this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js), my draft solution is: [codepen - react-bootstrap-table - CustomFilter min-max ](https://codepen.io/dlplenin/pen/wyaqaE?editors=0011)

The bad news for me is that Im working in outside (not into headers) filters, so this solution doesn't work for me (yet, I hope).

**Comment by quinnreed** [comment]
In case anyone new comes across this issue, it is fixed in the newest 3.0.0 release of react-bootstrap-table, and 1.1.5 for the filter package specifically. 
I am using a package [react-bootstrap-daterangepicker](https://github.com/skratchdot/react-bootstrap-daterangepicker) for the purpose of custom filtering my date column

```
const columns = [
      {
        ...
        filter: customFilter({
          type: FILTER_TYPES.DATE,
          onFilter:  filterVal => 
               DATA.filter(s => moment(s.DATE) > filterVal.startDate && moment(s.DATE) < filterVal.endDate.add(1, 'day'))
        }),
        filterRenderer: (onFilter, column) => 
          <DateRangeFilter onFilter={onFilter} column={column}/>
      }
    ];   
```

DateRangeFilter here is my custom component wrapping DateRangePicker. And startDate and endDate are return values from DateRangePicker.

**Comment by MufassirShaw** [comment]
For those of you who are still having trouble wrapper their heads around it. [Here ](https://codepen.io/Codershah/pen/vYBgRdY?editors=0011) is the solution, would recommend to use momentjs though.

**Comment by swatantra-happy** [comment]
> DateRangeFilter

please provide code for the <DateRangeFilter > component
