### ISSUE TITLE
Getting row index in dataFormat props function ?

### ISSUE THREAD

**Issue by akashshinde** [AllenFang/react-bootstrap-table#604]
I can see dataFormat props func expsoses cell and complete row object.
```javascript
 dataFormat(cell,row) {}
```

Is there any way to get row index here ?

**Comment by AllenFang** [comment]
@akashshinde, if pagination was enabled, the scope of row index is belong on current page?

**Comment by akashshinde** [comment]
@AllenFang yes, pagination is enabled as I am having less than 10 items rendered in table, So it's in current page.

**Comment by AllenFang** [comment]
@akashshinde, I can support this feature in next version.

**Comment by AllenFang** [comment]
Released on ```v2.4.0```, check this [example](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-format/get-row-index-table.js)

**Comment by akashshinde** [comment]
@AllenFang Thanks :)
Will check it out

**Comment by rayjsiu** [comment]
This is gold. Thanks @AllenFang

**Comment by Grinzzekatze** [comment]
Hi!
I tried the example but can´t get the row index. When I click my button the function “addRowSorted” only get´s something like this :

Index = Proxy {dispatchConfig : {…} , .. etc.}

What´s wrong with my code? Thanks!


function activeFormatter(cell, row, enumObject, index) {
    debugger;
    console.log(`The row index: ${index}`);
    return (
      <ActiveFormatter index={index } addRowSorted= {this.props.addRowSorted}/>
    );
  }

class ActiveFormatter extends React.Component {

    render() {

        return (
            <IconButton
                iconProps={{ iconName: 'Add' }}
                onClick={(index) => this.props.addRowSorted(index)}
            />
        );
    }
}

addRowSorted(index) {
        debugger;
        let resources = this.props.data.slice();
        var emptyLine = { id: _.random(-100000000000, 0) }
        resources.splice(index + 1, 0, emptyLine);
        // this.setState({ resources }, this.refs.table.added);
    }

**Comment by paradise5455** [comment]
@AllenFang , if the filter of the column is applied, and any filter is made, the row-id will not start with number "1" because the "ID" here is generated based on the product number. For e.g, if we filter the column "name" with value 4, the row id will will show "4". Since the ID is generated incremental, thus cannot deal with it.

Goal: Want to to have row_index for id add incremental, and even after filter the column name, the 1st row index will start/count as no.1. 

Question: 
If pagination is applied, the row index will always start with number 1, when we turn to page 2, or page 3. if we used own generated row index as below code, how can we fix that ?


For example code below, try to use this:

`indexNumber(cell, row, enumObject, rowIndex) {
    return (<div>{rowIndex + 1}</div>)
  }`


`<TableHeaderColumn ref='id' dataField="id" width='70px' dataSort  expandable={false}
              dataFormat={this.indexNumber}
            >
              ID
            </TableHeaderColumn>`
