### ISSUE TITLE
State modification using redux

### ISSUE THREAD

**Issue by edulis8** [AllenFang/react-bootstrap-table#618]
Hello,
I was playing around with the cell editing feature in a react/redux app. It looks like when you enable cell editing, react-bootsrap-table automatically mutates its input object to save the value. This doesn't really congrue with the idea of redux, which is supposed to manage state. Is there a way to disable the automatic mutation of the input dataset in react-bootstrap-table?

**Comment by rrameshkumar76** [comment]
one way may be you can use the beforeSaveCell and cancel the save(return false) and add your custom code to apply the edit changes and do a render. The event does give the row,cellname and modified cellvalue.
There may be a better way that i am not aware of.

**Comment by AllenFang** [comment]
@rrameshkumar76, thanks, your answer is a workaround and I thinks it's the only way to achieve this target currently.

BTW, ```react-bootstrap-table``` support the ```remote``` mode and this mode allow you to manage the state on your state manager(redux, mobx ..). However, we all support sorting, insert, delete, exportCSV .etc on ```remote``` mode, but missing cell editing(Because there's some issue that it's hard to explain).

Anyway, I'll try to make cell editing available on ```remote``` mode, I think it will fix this issue

Thanks 👍

**Comment by edulis8** [comment]
Hello,
I am also wondering how I can change the default amount of rows shown when pagination is enabled. I’d like 20 or 30 rows to be shown per page by default instead of 10.

**Comment by AllenFang** [comment]
@edulis8, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/pagination/custom-pagination-table.js#L35

**Comment by AllenFang** [comment]
Fixed on ```v2.4.2```. https://github.com/AllenFang/react-bootstrap-table/commit/f399e878102322f3da68f95c1265b5c27e1eba1b is an example for demo how to use cell edit on ```remote``` mode

**Comment by rrameshkumar76** [comment]
Thanks for the nice remote mode.It helps us a lot.

**Comment by MedinaGitHub** [comment]
remoto with event selectRow works?
