### ISSUE TITLE
[CSS] Module not found when webpack css-loader

### ISSUE THREAD

**Issue by io3** [AllenFang/react-bootstrap-table#66]
```
Module not found: Error: Cannot resolve 'file' or 'directory' ../node_modules/toastr/build/toastr.min.css in rea
ct-bootstrap-table\css
 @ ./~//react-component-tools/~/css-loader!./~//react-component-tools/~/autoprefixer-loader?browsers=last 2 version!./~/react-bootstrap-table/css/react-bootstra
p-table.css 3:10-135
```

my deps:
```
"react-bootstrap-table": "^1.0.1",
"toastr": "2.1.2"
```

```
import 'react-bootstrap-table/css/react-bootstrap-table.css';
```

**Comment by AllenFang** [comment]
HI @io3 , can you try to import <code>react-bootstrap-table.min.css</code>

**Comment by io3** [comment]
the same error too

**Comment by AllenFang** [comment]
can you try add less-loader again for a temporary work, I think theres some mistake in my css bundling process. sorry ;(   I'll fix it quickly

**Comment by AllenFang** [comment]
hi @io3 , use <code>v1.0.2</code> again

**Comment by io3** [comment]
`@import "../node_modules/toastr/build/toastr.min.css";` can not exits in /css/react-bootstrap-table.css.
Because i depend `toastr` immediate.

**Comment by AllenFang** [comment]
hi @io3, I think you should import <code>react-bootstrap-table.min.css</code>. because <code>react-bootstrap-table.css</code> include the code <code>@import "../node_modules/toastr/build/toastr.min.css"</code>, but it's not resolve and bundle, so use the <code>react-bootstrap-table.min.css</code> which is bundling. The bug you found is a PR add <code>@import "../node_modules/toastr/build/toastr.min.css"</code> but I don't notice it. Anyway I've concat the react-bootstrap-table.css and toastr.min.css in <code>react-bootstrap-table.min.css</code>, so include <code>react-bootstrap-table.min.css</code> should solve this issues

**Comment by io3** [comment]
但是如果我引用了toastr的css的话，会重复加载css

**Comment by AllenFang** [comment]
you're right, but I think it's another issue about loading <code>toastr</code> css with <code>react-bootstrap-table</code>. I'll find some solutions like separate the <code>toastr</code> and <code>react-bootstrap-table</code> css code or something like that. which you can choice what bundling css you want to import, but it need some times, However I want to know there's no any error for using <code>react-bootstrap-table</code>?

**Comment by io3** [comment]
这肯定是没问题的

**Comment by AllenFang** [comment]
Thanks you feedback :)  I will open another issue for the <code>toastr</code> problem and fix it
