### ISSUE TITLE
Stacked style in mobile version

### ISSUE THREAD

**Issue by gravitycode** [AllenFang/react-bootstrap-table#662]
Hi!
thank for your great contribution. Im trying to customize by css the behavior in small devices. My intention is to make something like https://codepen.io/nhackley/pen/QbGoLN but with the implementation of react-bootstrap-table with two tables (one for head and one for body) not is possible. Is there any way to do this? Thank you.

**Comment by AllenFang** [comment]
@gravitycode sorry for lately reply and there's no way to do this. maybe PR is welcome :)

**Comment by gravitycode** [comment]
Thanks Allen! 
Do you think we should go to a more standard html table? One <table> for each instance

**Comment by AllenFang** [comment]
@gravitycode, surely, but the horizonal and vertical scroll make me hard to do that under bootstrap.

That's said, I'm not very master on css and bootstrap, so if you know how to do it or a nice example for me, I can try it on ```v3.0.0```.  

BTW, I know there are some issues like unalign column all caused by two table structure, so I also hate this structure... ;(
