### ISSUE TITLE
 Need help at sorting 

### ISSUE THREAD

**Issue by Divyansh1605** [AllenFang/react-bootstrap-table#663]
I am able to sort when my remote prop is false, as i want remote functionalities and make it to true i m not able to sort, icon does not change and onSortChange callback only gives desc.

**Comment by AllenFang** [comment]
@Divyansh1605, you need to figure out what's ```remote```. Actually, it's means you need to handle all the state changing(filter, search, sort, pagination, insert etc.) instead of handled by ```react-bootstrap-table```.

[There](https://github.com/AllenFang/react-bootstrap-table/tree/master/examples/js/remote)'re  a lots of examples for remoting.
