### ISSUE TITLE
Set class for css styles on a cell or row based on data

### ISSUE THREAD

**Issue by udalrich** [AllenFang/react-bootstrap-table#674]
I would like to be able to do something like this.

    const data = [ 
        { x: 1, y: 2},
        { x: 2, y: 3}
    ];

    const getClass = (cell, row) {
        if (row.x == 1) { 
           return "bg-info";
        } else {
           return "bg-warning";
        }
    }

    const MyTable = () => (
        <BootstrapTable data={data} keyField="x">
            <TableHeaderColumn dataField="y" **dataClass={getClass}** />
        </BootstrapTable>
    );

When rendered, `MyTable` would have the `bg-info` class on the first row and `bg-warning` on the second row. This would result in the background of the cells being colored appropriately.

I tried setting `dataFormat={cellFormat}` on the columns, where `cellFormat` returns ` <span bsClass="{style}"> {cell} </span>` with style being the style name, but that did not work.  Setting `class` instead of `bsClass` also did not work.

**Comment by AllenFang** [comment]
@udalrich, check https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/style/tr-class-function-table.js and https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/style/td-class-function-table.js

**Comment by patrickgordon** [comment]
hey @AllenFang what about if you also use sort? Because the styling is done on the index, after sorting the style will still be on the same index.

In this example, only rows which have "no time clocked" in both "actual start" and "actual finish", should be red. But if I sort, the row in the now new position is red:
https://i.gyazo.com/43b585e6e06ebdefc6cf48628517b4e3.gif

Any ideas?

**Comment by AllenFang** [comment]
Hi @patrickgordon, did you use ```trClassFormat``` to custom the *red row* which have no start and end time?  If yes, ```trClassFormat``` have two arguments, ```rowData``` and ```rowIndex```, so I think you should use ```rowData``` to check if it should be mark as red instead ```rowIndex```.

Feel free to discuss with me :)

**Comment by patrickgordon** [comment]
hey @AllenFang here's what I did:
```
  trClassFormat(rowData, rIndex) {
    const {noShiftDataRowIds} = this.props
    if (find(noShiftDataRowIds, (item) => {
        return item === rIndex
      })) {
      return 'danger'
    }
  }
```

I think the issue is actually that `noShiftDataRowIds` is an array of the index's for my data and that is not changing because it has no reason to. What I will do is instead of it being an array of index I will make it an array of the primary key instead and that should work. :)

👍  thanks for help

**Comment by AllenFang** [comment]
@patrickgordon, yap. Hope you can get this job done 👍

**Comment by patrickgordon** [comment]
Yep all sorted @AllenFang !
