### ISSUE TITLE
Custom column filter and refs

### ISSUE THREAD

**Issue by oakley808** [AllenFang/react-bootstrap-table#749]
I'm getting the ESLint error message `react/no-string-refs` regarding the use of `this.refs`

https://github.com/AllenFang/react-bootstrap-table/blob/a1f1e077c23065eb4e2c81f3cfb92ba29e96bf3a/examples/js/column-filter/custom-filter.js#L38-L53 
Is there another recommended way to handle this? I'd like to loop over a dynamic list of checkboxes instead of just two yes/no checkboxes.

BTW, this is great functionality @dana2208 ! I'm trying to use it to create a dynamic multiselects on each column.

**Comment by AllenFang** [comment]
@oakley808, sorry for lately reply. because refs accept a callback(that's prefer) or a string, so you can use callback instead(check the react [doc](https://facebook.github.io/react/docs/more-about-refs.html#the-ref-callback-attribute)).

Feel free to discuss with me if you still got the trouble. Thanks 👍
