### ISSUE TITLE
replace "Add new Modal" to add one row in the table?

### ISSUE THREAD

**Issue by sunnyzhang66** [AllenFang/react-bootstrap-table#757]
is that possible instead using Modal for "Add new record" and insert new row to table?

thanks

**Comment by AllenFang** [comment]
you means click the insert row button but you dont want to use the default modal for row adding?

**Comment by gforge** [comment]
Perhaps unrelated to this issue but if possible I would like to be able to substitute the current modal with my own modal form. I started using `react-bootstrap-table` a couple days ago and the package is great but solving everything in one package may be a lot to ask, especially since you get unexpected bugs such as the #690. Providing your own editor would therefore be an interesting feature in my mind.


### Suggestion

A simple alternative could be to check if the `enableInsert` is a function and then use that at the `onClick` event [here](https://github.com/AllenFang/react-bootstrap-table/blob/master/src/toolbar/ToolBar.js#L203-L208). By adding a flexible proptype:

```js
React.PropTypes.oneOfType([
    React.PropTypes.bool,
    React.PropTypes.func
])
```

The component would simply be:


```js
insertBtn = (
        <button type='button'
          className='btn btn-info react-bs-table-add-btn'
          {typeof enableInsert === "boolean" &&
          data-toggle='modal'
          data-target={ '.' + this.modalClassName }> }
          {typeof enableInsert === "function" &&
          onClick={enableInsert}}
          <i className='glyphicon glyphicon-plus'></i> { this.props.insertText }
        </button>
      );
```

Thanks for the excellent work and I love the package!

**Comment by AllenFang** [comment]
@gforge, sorry for lately reply. Thanks your suggestion, The ```v3.0.0``` will tackle these custom issue, 

Feel Free to discuss with me, close this issue cause of @sunnyzhang66 have no any response.
