### ISSUE TITLE
TableRow doesn't have a key attribute!

### ISSUE THREAD

**Issue by innopal** [AllenFang/react-bootstrap-table#775]
This causes a warning:
warning: flattenChildren(...): Encountered two children with the same key, `undefined`. Child keys must be unique; when two children share a key, only the first child will be used.

It's probably just react 15 thing but it is a good practice to add keys to children.

Cheers

**Comment by abachman** [comment]
I just had the same problem and went digging. 

It looks like the problem was on my end, I either needed to pass in a `keyField` value with the BootstrapTable component or add an `isKey` prop to the TableHeaderColumn component with the appropriate `dataField` value.

So, 
```jsx
<BoostrapTable data={data} keyField='id'>
  <TableHeaderColumn dataField="id">ID</TableHeaderColumn>
  <TableHeaderColumn dataField="name">Name</TableHeaderColumn>
</BootstrapTable>
```
and 
```jsx
<BoostrapTable data={data}>
  <TableHeaderColumn dataField="id" isKey>ID</TableHeaderColumn>
  <TableHeaderColumn dataField="name">Name</TableHeaderColumn>
</BootstrapTable>
```
have the same effect. 

**My specific problem** was that the `isKey` value was set on a TableHeaderColumn whose `dataField` didn't appear in the data collection I passed to the BoostrapTable. That meant the TableRows were rendering properly, but keys were all being set to undefined.

Hopefully that helps.

**Comment by innopal** [comment]
Thank you @abachman ,

You are correct! When your key column is hidden it throws that warning.

So what did you end up doing? I don't want to display my unique key column and I don't have any other unique column.

Cheers

**Comment by AllenFang** [comment]
@innopal, did you make the key column as hidden so cause this issue? (Because I cant reproduce it)

I think if you really have no any field as key column, just make one as sequence number and hide it.

Feel free to discuss with me.

**Comment by abachman** [comment]
@innopal in my case, I had to make sure that the `dataField` pointed to by the `isKey` TableHeaderColumn was present in the data. We were using "name" in the dataField prop, but "id" in the `dataFormat` of that column and our records included an `id` attribute but not `name`, so the bug only showed up in the console and not visually (on the page).

Just playing with it, it looks like using the `keyField` prop of the top-level BootstrapTable component will let you use any field that's present in data, even if you don't include it as a TableHeaderColumn.

**Comment by innopal** [comment]
Thank you @AllenFang and @abachman.

The bug always shows up on the console. I thought I was clear about that.
keyField of isKey behave the same, neither made the warning go away.

Cheers
