### ISSUE TITLE
Install fails in restricted network environment (proxied npm registry)

### ISSUE THREAD

**Issue by lukateake** [AllenFang/react-bootstrap-table#861]
@AllenFang, by [adding a dependency](https://github.com/AllenFang/react-bootstrap-table/blob/master/package.json#L70) to an unreleased version, our install fails in a network restricted environment.

Please see this NPM post on how to deal with this issue:
http://blog.npmjs.org/post/145724408060/dealing-with-problematic-dependencies-in-a

> It’s usually a good idea to open an issue on the project with the Git dependency, politely asking the maintainers to replace the Git dependency, if possible. Generally, we discourage using Git dependencies in package.json, and it’s typically only used temporarily while a maintainer waits for an upstream fix to be applied and published.

**Comment by AllenFang** [comment]
@lukateake, it’s typically only used temporarily while a maintainer waits for an upstream fix to be applied and published.  that's the reason that I use git dependency. check #838 

Anyway, I'll check this out. Thanks.

**Comment by tplummerfni** [comment]
Second this.  We're running through a local NPM Registry.  Our build server does not have access to github.  I was under the impression that a Private Registry would cache even the git modules, but what appears to be happening is the client is ignoring the cached version and going for github.

**Comment by AllenFang** [comment]
Hi all, sorry for lately fixing.... Released on ```v2.7.0```, check this out, I've packaged the ```react-toastr``` as a scope module. Let me know if problem still remain. thanks

**Comment by af-fess** [comment]
I still get the same issue, I use latest version `2.8.2` with dependancies:

```
  "react": "^0.14.7",
    "react-bootstrap": "^0.30.7",
    "react-bootstrap-table": "^2.8.2",
    "react-dom": "~0.14.7",
```
Inside `react-bootstrap-table`:

```
  "dependencies": {
    "classnames": "^2.1.2",
    "@allenfang/react-toastr": "2.8.2"
  },
```

```
Error in compilation in webpack: ModuleNotFoundError: 
Module not found:
 Error: Cannot resolve module 'react-dom/lib/getVendorPrefixedEventName' in /Users/.../client/node_modules/react-bootstrap-table/node_modules/@allenfang/react-toastr/node_modules/react/lib

/Users/.../client/webpack.vendors.config.js:56
                    throw new Error('Error in compilation in webpack: ' + stats.compilation.errors);

```

**Comment by lukateake** [comment]
@AllenFang, this is still a problem for us even with the scope packaging, unfortunately.

Would you be amenable to removing the `react-toastr` dependency all together? I thought I saw somewhere that you're looking for PR help to that effect.

I'm happy to take a cut at it but could use a little guidance on how you'd prefer me to proceed.

**Comment by AllenFang** [comment]
For this issue, maybe you can check https://github.com/AllenFang/react-bootstrap-table/issues/1152

And for `react-toastr`, That's my thought, It's a pretty bad idea to depend with `react-toastr`, I should make the display message much customizable and use a more simple way to show the message(Like window.confirm or native bootstrap modal), but I didn't. And `react-toastr` was be depended for a long time, if I remove it now, I think there're a lots of people to concern. But actually I really really want to remove it :)

Anyway, I've planned to create `react-bootstrap-table2` to fix some critical bug(unalign issues and related issues) and it'll be a big change because the DOM and table structure will be different. So in `react-bootstrap-table2`, I also want to remove `react-toastr` and maybe support the fixed column, column resize etc. Anyway, It still on plan, but for me, I may not consider to remove `react-toastr` in this project or event in next major version, it's a big impact for all user

**Comment by AllenFang** [comment]
please check #1216, if you have any concern or question, let me know in #1216
