### ISSUE TITLE
Datepicker Only for Date

### ISSUE THREAD

**Issue by cristina321** [AllenFang/react-bootstrap-table#949]
Hi AllenFang and a datepicker only for date and not hours?

**Comment by AllenFang** [comment]
just like this: ```2014-11-11T15:25:33``` so what's your requirement?

**Comment by cristina321** [comment]
You can select only the date without any time. Currently if you do not add the time the data is not sent.

I propose a date selector without hours.

**Comment by cristina321** [comment]
I want to be able to select only the date

**Comment by AllenFang** [comment]
@cristina321, `react-bootstrap-table` use the default date input like [this](http://www.w3schools.com/html/tryit.asp?filename=tryhtml_input_date) and it's impossible to change the date format, due to [this](http://stackoverflow.com/questions/7372038/is-there-any-way-to-change-input-type-date-format). Anyway, we support this basic functionality and if you think it's not suitable for your application, I recommend you to custom your date picker, check [this](https://github.com/AllenFang/react-bootstrap-table/blob/master/examples/js/column-filter/custom-filter.js) to see how to custom.

BTW, there's a best solution which is I can find a react datepicker library and integrate with it, but I thought this is not a critical feature currently and it's also a dependency for this repo and I need to master it so that I can integrate it with this component well. So PR is welcome

Let me know if you have any question,
